### ISSUE TITLE
Impossible to disable some services

### ISSUE THREAD

**Issue by mitchoum** [10se1ucgo/DisableWinTracking#114]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Pro
* Architecture (32bit/64bit): 64 bit
* Options used: disable all except "Uninstall OneDrive"

**LOG:**
Services: Diagnostics Tracking Service unable to be stopped.
DiagTrack Log: Unable to clear/lock
Services: dmwappushsvc unable to be stopped.
Services: Diagnostics Tracking Service unable to be stopped.

```python

10:00:07 INFO: Performing clutter control

10:00:08 INFO: DiagTrack box ticked

10:00:08 ERROR: Services: Diagnostics Tracking Service unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 474, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'Le service sp\xe9cifi\xe9 n\x92existe pas en tant que service install\xe9.')

10:00:08 ERROR: DiagTrack Log: Unable to clear/lock.
Traceback (most recent call last):
  File "<string>", line 453, in cleardiagtracklog
IOError: [Errno 13] Permission denied: 'C:\\ProgramData\\Microsoft\\Diagnosis\\ETLLogs\\AutoLogger\\AutoLogger-Diagtrack-Listener.etl'

10:00:08 INFO: Service disable option ticked

10:00:08 ERROR: Services: dmwappushsvc unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 474, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 320, in ControlService
error: (1062, 'ControlService', 'Le service n\x92a pas \xe9t\xe9 d\xe9marr\xe9.')

10:00:08 ERROR: Services: Diagnostics Tracking Service unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 474, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'Le service sp\xe9cifi\xe9 n\x92existe pas en tant que service install\xe9.')

10:00:08 INFO: DisableWinTracking Version: v2.5.1

10:00:08 INFO: Mode: Privacy

10:00:08 INFO: Telemetry box ticked

10:00:08 INFO: Host box ticked

10:00:08 INFO: Extra host box ticked

10:00:08 INFO: IP block box ticked

10:00:08 INFO: Defender/Wifisense box ticked

10:00:08 ERROR: Registry: Unable to modify Windows Defender Spynet key.
Traceback (most recent call last):
  File "<string>", line 575, in modifyregistry
WindowsError: [Error 5] Accès refus

10:00:08 ERROR: Registry: Unable to modify Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "<string>", line 575, in modifyregistry
WindowsError: [Error 5] Accès refus

```

**Comment by Ruined1** [comment]
@mitchoum Have you run any version of DWT before? If so these are to be expected.

**Comment by 10se1ucgo** [comment]
Fixed.
