### ISSUE TITLE
Lots of error messages in 3.0

### ISSUE THREAD

**Issue by miri4ever** [10se1ucgo/DisableWinTracking#156]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
23:40:35 INFO: Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32
23:40:35 INFO: uname_result(system='Windows', node='Neptune', release='10', version='10.0.10586', machine='AMD64', processor='Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')
23:40:35 INFO: DisableWinTracking version 3.0
23:41:04 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 254, in go
  File "dwt_util.py", line 45, in ip_block
  File "subprocess.py", line 629, in check_output
  File "subprocess.py", line 696, in run
  File "subprocess.py", line 914, in __init__
  File "subprocess.py", line 1113, in _get_handles
OSError: [WinError 6] Das Handle ist ungültig

23:41:31 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 254, in go
  File "dwt_util.py", line 45, in ip_block
  File "subprocess.py", line 629, in check_output
  File "subprocess.py", line 696, in run
  File "subprocess.py", line 914, in __init__
  File "subprocess.py", line 1113, in _get_handles
OSError: [WinError 6] Das Handle ist ungültig

23:41:36 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 254, in go
  File "dwt_util.py", line 45, in ip_block
  File "subprocess.py", line 629, in check_output
  File "subprocess.py", line 696, in run
  File "subprocess.py", line 914, in __init__
  File "subprocess.py", line 1113, in _get_handles
OSError: [WinError 6] Das Handle ist ungültig

23:41:44 CRITICAL: Traceback (most recent call last):
  File "dwt_util.py", line 76, in delete_service
  File "site-packages\win32\lib\win32serviceutil.py", line 302, in RemoveService
  File "site-packages\win32\lib\win32serviceutil.py", line 80, in SmartOpenService
pywintypes.error: (1060, 'GetServiceKeyName', 'Der angegebene Dienst ist kein installierter Dienst.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dwt.py", line 260, in go
  File "dwt_util.py", line 80, in delete_service
  File "dwt_util.py", line 80, in <genexpr>
TypeError: 'error' object does not support indexing

23:41:48 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 256, in go
  File "dwt_util.py", line 59, in clear_diagtrack
  File "subprocess.py", line 629, in check_output
  File "subprocess.py", line 696, in run
  File "subprocess.py", line 914, in __init__
  File "subprocess.py", line 1113, in _get_handles
OSError: [WinError 6] Das Handle ist ungültig

23:41:53 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
23:41:53 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions
23:42:02 INFO: Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32
23:42:02 INFO: uname_result(system='Windows', node='Neptune', release='10', version='10.0.10586', machine='AMD64', processor='Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')
23:42:02 INFO: DisableWinTracking version 3.0
23:42:06 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 254, in go
  File "dwt_util.py", line 45, in ip_block
  File "subprocess.py", line 629, in check_output
  File "subprocess.py", line 696, in run
  File "subprocess.py", line 914, in __init__
  File "subprocess.py", line 1113, in _get_handles
OSError: [WinError 6] Das Handle ist ungültig

23:42:10 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
23:42:10 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions
23:42:17 INFO: Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32
23:42:17 INFO: uname_result(system='Windows', node='Neptune', release='10', version='10.0.10586', machine='AMD64', processor='Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')
23:42:17 INFO: DisableWinTracking version 3.0
23:42:32 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 276, in go
  File "dwt_util.py", line 161, in onedrive
  File "shlex.py", line 273, in split
  File "shlex.py", line 263, in __next__
  File "shlex.py", line 90, in get_token
  File "shlex.py", line 118, in read_token
AttributeError: 'set' object has no attribute 'read'

23:42:36 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
23:42:36 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions
23:44:09 INFO: Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32
23:44:09 INFO: uname_result(system='Windows', node='Neptune', release='10', version='10.0.10586', machine='AMD64', processor='Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')
23:44:09 INFO: DisableWinTracking version 3.0
23:44:14 CRITICAL: Traceback (most recent call last):
  File "dwt_util.py", line 76, in delete_service
  File "site-packages\win32\lib\win32serviceutil.py", line 302, in RemoveService
  File "site-packages\win32\lib\win32serviceutil.py", line 80, in SmartOpenService
pywintypes.error: (1060, 'GetServiceKeyName', 'Der angegebene Dienst ist kein installierter Dienst.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dwt.py", line 259, in go
  File "dwt_util.py", line 80, in delete_service
  File "dwt_util.py", line 80, in <genexpr>
TypeError: 'error' object does not support indexing

23:44:32 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 256, in go
  File "dwt_util.py", line 59, in clear_diagtrack
  File "subprocess.py", line 629, in check_output
  File "subprocess.py", line 696, in run
  File "subprocess.py", line 914, in __init__
  File "subprocess.py", line 1113, in _get_handles
OSError: [WinError 6] Das Handle ist ungültig

23:44:38 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
23:44:38 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions

```

**Comment by 10se1ucgo** [comment]
huh. weird. ill look into it

**Comment by WillPresley** [comment]
FWIW, I am having the same issues with 3.0.

**Comment by 10se1ucgo** [comment]
[Yup, I know why, I fixed a similar issue I had with pyjam this way](https://github.com/10se1ucgo/pyjam/commit/08b8bf6d097110817e4b61ae4ddd64d42489b8ef)

I'll push a commit once I'm not lazy

**Comment by WillPresley** [comment]
Nice! Thanks for fixing this stuff up. I'm away from my build env. at the moment, any chance we could get an updated executable? I have no idea how long that takes on your side, so if not it's not a worry.

**Comment by 10se1ucgo** [comment]
Will do in a little bit

**Comment by 10se1ucgo** [comment]
Having some issues with building, might not be able to until tomorrow.

**Comment by MarcinJanowski** [comment]
Hello, i have similary error:
```
13:00:11 INFO: Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32
13:00:11 INFO: uname_result(system='Windows', node='LUBN366', release='10', version='10.0.10586', machine='AMD64', processor='Intel64 Family 6 Model 78 Stepping 3, GenuineIntel')
13:00:11 INFO: DisableWinTracking version 3.0
13:03:13 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 254, in go
  File "dwt_util.py", line 45, in ip_block
  File "subprocess.py", line 629, in check_output
  File "subprocess.py", line 696, in run
  File "subprocess.py", line 914, in __init__
  File "subprocess.py", line 1113, in _get_handles
OSError: [WinError 6] The handle is invalid

13:03:22 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 254, in go
  File "dwt_util.py", line 45, in ip_block
  File "subprocess.py", line 629, in check_output
  File "subprocess.py", line 696, in run
  File "subprocess.py", line 914, in __init__
  File "subprocess.py", line 1113, in _get_handles
OSError: [WinError 6] The handle is invalid

```

**Comment by 10se1ucgo** [comment]
Fixed: https://github.com/10se1ucgo/DisableWinTracking/releases/tag/v3.0.1
