### ISSUE TITLE
CRITICAL: Traceback

### ISSUE THREAD

**Issue by BenUtzmich** [10se1ucgo/DisableWinTracking#159]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**
14:44:26 INFO: Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32
14:44:26 INFO: uname_result(system='Windows', node='C3P0-R2D2', release='10', version='10.0.10586', machine='AMD64', processor='Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
14:44:26 INFO: DisableWinTracking version 3.0
14:45:46 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 254, in go
  File "dwt_util.py", line 45, in ip_block
  File "subprocess.py", line 629, in check_output
  File "subprocess.py", line 696, in run
  File "subprocess.py", line 914, in __init__
  File "subprocess.py", line 1113, in _get_handles
OSError: [WinError 6] Das Handle ist ungültig

14:46:00 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 254, in go
  File "dwt_util.py", line 45, in ip_block
  File "subprocess.py", line 629, in check_output
  File "subprocess.py", line 696, in run
  File "subprocess.py", line 914, in __init__
  File "subprocess.py", line 1113, in _get_handles
OSError: [WinError 6] Das Handle ist ungültig

14:46:30 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 256, in go
  File "dwt_util.py", line 59, in clear_diagtrack
  File "subprocess.py", line 629, in check_output
  File "subprocess.py", line 696, in run
  File "subprocess.py", line 914, in __init__
  File "subprocess.py", line 1113, in _get_handles
OSError: [WinError 6] Das Handle ist ungültig

14:46:33 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 256, in go
  File "dwt_util.py", line 59, in clear_diagtrack
  File "subprocess.py", line 629, in check_output
  File "subprocess.py", line 696, in run
  File "subprocess.py", line 914, in __init__
  File "subprocess.py", line 1113, in _get_handles
OSError: [WinError 6] Das Handle ist ungültig

14:46:52 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 256, in go
  File "dwt_util.py", line 59, in clear_diagtrack
  File "subprocess.py", line 629, in check_output
  File "subprocess.py", line 696, in run
  File "subprocess.py", line 914, in __init__
  File "subprocess.py", line 1113, in _get_handles
OSError: [WinError 6] Das Handle ist ungültig

14:46:58 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
14:46:58 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions

**Comment by 10se1ucgo** [comment]
Fixed in ada20b4. Uploading release as soon as I get my virtualenv running.

**Comment by 10se1ucgo** [comment]
https://github.com/10se1ucgo/DisableWinTracking/releases/tag/v3.0.1
