### ISSUE TITLE
Cant update win defender

### ISSUE THREAD

**Issue by JorisBolsens** [10se1ucgo/DisableWinTracking#169]
**INFORMATION:**
- Windows Edition (Home/Pro/Enterprise):
- Architecture (32bit/64bit):
- Options used:

**LOG:**

``` python
00:15:53 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
00:15:53 INFO: ('Windows', 'NAME', '10', '10.0.10586', 'AMD64', 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
00:15:53 INFO: DisableWinTracking version 3.0.1
00:16:42 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
00:16:42 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
00:16:42 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
00:16:42 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
00:16:42 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
00:16:42 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
00:16:42 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
00:16:42 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
00:16:42 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
00:16:42 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
00:16:42 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
00:16:43 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
00:16:43 CRITICAL: DiagTrack: Error output:

00:16:43 INFO: Services: Succesfully removed service 'dmwappushsvc'
00:16:43 INFO: Services: Succesfully removed service 'DiagTrack'
00:16:43 INFO: Registry: Successfully modified dmwappushsvc key.
00:16:43 INFO: Registry: Successfully modified DiagTrack key.
00:16:43 INFO: Registry: Successfully modified AllowTelemetry key.
00:16:43 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
00:16:43 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
00:16:43 INFO: Registry: Successfully modified Windows Defender Delivery Optimization Download key.
00:16:43 INFO: Registry: Successfully modified WifiSense Open-ness key.
00:16:43 INFO: Registry: Successfully modified WifiSense Credential Share key.
00:16:43 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
00:16:43 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions

```

**Comment by ascensionra** [comment]
I also have this issue. Did not submit separate issue report.
