### ISSUE TITLE
Access Denied While Attempting Changes 

### ISSUE THREAD

**Issue by notnola** [10se1ucgo/DisableWinTracking#171]
**INFORMATION:**
- Windows Edition (Home/Pro/Enterprise): Windows 10 Enterprise LTSB N 2015 (All major updates/preboot malware protection disabled/driver verification disabled)
- Architecture (32bit/64bit): 64bit.
- Options used:![image](https://cloud.githubusercontent.com/assets/9591067/15269581/5a7bd3ce-19d1-11e6-84aa-5b53539515fe.png)

**LOG:**

``` python
12:39:36 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
12:39:36 INFO: ('Windows', '<my_host_name>', '10', '10.0.10240', 'AMD64', 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
12:39:36 INFO: DisableWinTracking version 3.0.1
12:39:57 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
12:39:58 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
12:39:58 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
12:39:58 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
12:39:59 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
12:39:59 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
12:39:59 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
12:40:00 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
12:40:00 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
12:40:00 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
12:40:01 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
12:40:01 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
12:40:01 CRITICAL: DiagTrack: Error output:

12:40:01 INFO: Registry: Successfully modified dmwappushsvc key.
12:40:01 INFO: Registry: Successfully modified DiagTrack key.
12:40:01 INFO: Registry: Successfully modified AllowTelemetry key.
12:40:01 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
12:40:01 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
12:40:01 INFO: Registry: Successfully modified Windows Defender Delivery Optimization Download key.
12:40:01 INFO: Registry: Successfully modified WifiSense Open-ness key.
12:40:01 INFO: Registry: Successfully modified WifiSense Credential Share key.
12:40:01 INFO: Registry: Successfully modified ListPin key.
12:40:01 INFO: Registry: Successfully modified FileSync key.
12:40:01 INFO: OneDrive: unable to install
12:40:01 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
12:40:01 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions
```

**Comment by woojoo666** [comment]
same issue with the Diagnostic log, though I didn't try to uninstall onedrive so don't know about that one

**Comment by 10se1ucgo** [comment]
All normal if you've run the program before. Have you?
