### ISSUE TITLE
Issue with windows defender. It said that this EXE is a trojan and would not allow me to execute

### ISSUE THREAD

**Issue by ageisen2000** [10se1ucgo/DisableWinTracking#176]
**INFORMATION:**

* Windows Edition (Pro):
* Architecture (64bit):
* Options used:

**LOG:**
N/A but I've included below 

```python
21:57:11 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
21:58:39 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
21:58:39 CRITICAL: DiagTrack: Error output:
21:58:39 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
21:58:39 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
21:58:39 INFO: Registry: Successfully modified Windows Defender Delivery Optimization Download key.
21:58:39 INFO: Registry: Successfully modified WifiSense Open-ness key.
21:58:39 INFO: Registry: Successfully modified WifiSense Credential Share key.
21:58:39 INFO: Registry: Successfully modified ListPin key.
21:58:39 INFO: Registry: Successfully modified FileSync key.
21:58:39 INFO: OneDrive: unable to uninstall
21:58:39 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
21:58:39 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions

```

**Comment by 10se1ucgo** [comment]
168

**Comment by ageisen2000** [comment]
Sorry about that. Didn't realize another ticket was opened already.

**Comment by 10se1ucgo** [comment]
Don't worry, it's no problem.
