### ISSUE TITLE
DiagTrack: Failed to clear DiagTrack log

### ISSUE THREAD

**Issue by feldrim** [10se1ucgo/DisableWinTracking#179]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): W10 Home
* Architecture (32bit/64bit): 32-Bit
* Options used: All checkboxes set to disable in privacy mode.

**LOG:**

```python
01:26:27 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
01:26:27 INFO: ('Windows', 'LG', '10', '10.0.10586', 'x86', 'x86 Family 6 Model 37 Stepping 2, GenuineIntel')
01:26:27 INFO: DisableWinTracking version 3.0.1
01:28:40 INFO: Successfully removed app 'getstarted'
01:28:40 INFO: Successfully removed app 'bingnews'
01:28:40 INFO: Successfully removed app 'zunevideo'
01:28:40 INFO: Successfully removed app 'windowsphone'
01:28:40 INFO: Successfully removed app 'skypeapp'
01:28:40 INFO: Successfully removed app 'bingfinance'
01:28:40 INFO: Successfully removed app 'solitairecollection'
01:28:40 INFO: Successfully removed app 'officehub'
01:28:40 INFO: Successfully removed app 'bingweather'
01:28:40 INFO: Successfully removed app 'zunemusic'
01:28:40 INFO: Successfully removed app 'photos'
01:28:40 INFO: Successfully removed app '3dbuilder'
01:28:40 INFO: Successfully removed app 'xboxapp'
01:28:40 INFO: Successfully removed app 'soundrecorder'
01:28:40 INFO: Successfully removed app 'onenote'
01:28:40 INFO: Successfully removed app 'windowscommunicationsapps'
01:28:40 INFO: Successfully removed app 'windowsmaps'
01:28:40 INFO: Successfully removed app 'sway'
01:28:40 INFO: Successfully removed app 'bingsports'
01:28:40 INFO: Successfully removed app 'people'
01:28:40 INFO: Successfully removed app 'windowscamera'
01:29:19 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
01:29:20 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
01:29:20 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
01:29:20 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
01:29:20 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
01:29:20 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
01:29:20 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
01:29:20 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
01:29:21 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
01:29:21 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
01:29:21 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
01:29:21 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
01:29:21 CRITICAL: DiagTrack: Error output:

01:29:22 INFO: Services: Succesfully removed service 'dmwappushsvc'
01:29:22 INFO: Services: Succesfully removed service 'DiagTrack'
01:29:22 INFO: Registry: Successfully modified dmwappushsvc key.
01:29:22 INFO: Registry: Successfully modified DiagTrack key.
01:29:22 INFO: Registry: Successfully modified AllowTelemetry key.
01:29:22 INFO: Registry: Successfully modified Windows Defender Delivery Optimization Download key.
01:29:22 INFO: Registry: Successfully modified WifiSense Open-ness key.
01:29:22 INFO: Registry: Successfully modified WifiSense Credential Share key.
01:29:22 INFO: Registry: Successfully modified ListPin key.
01:29:22 INFO: Registry: Successfully modified FileSync key.
01:29:22 INFO: OneDrive: unable to uninstall
01:29:22 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
01:29:22 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions

```

**Comment by 10se1ucgo** [comment]
Normal if you've run the program before.
