### ISSUE TITLE
Windows update - Installation Failure

### ISSUE THREAD

**Issue by lenisko** [10se1ucgo/DisableWinTracking#194]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): 10 Edu
* Architecture (32bit/64bit): 64bit
* Options used: As shown in log

**PROBLEM:**
```
Installation Failure: Windows failed to install the following update with error 0x800F0922: Cumulative Update for Windows 10 Version 1511 for x64-based Systems (KB3172985).
```

**LOG:**

```
05:28:05 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
05:28:05 INFO: ('Windows', 'DESKTOP-D1QMACN', '10', '10.0.10586', 'AMD64', 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel')
05:28:05 INFO: DisableWinTracking version 3.0.1
05:29:29 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
05:29:29 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
05:29:29 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
05:29:29 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
05:29:29 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
05:29:30 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
05:29:30 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
05:29:30 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
05:29:30 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
05:29:30 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
05:29:30 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
05:29:30 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
05:29:30 CRITICAL: DiagTrack: Error output:

05:29:30 INFO: Services: Succesfully removed service 'dmwappushsvc'
05:29:30 INFO: Services: Succesfully removed service 'DiagTrack'
05:29:30 INFO: Registry: Successfully modified dmwappushsvc key.
05:29:30 INFO: Registry: Successfully modified DiagTrack key.
05:29:30 INFO: Registry: Successfully modified AllowTelemetry key.
05:29:30 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
05:29:30 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
05:29:30 INFO: Registry: Successfully modified Windows Defender Delivery Optimization Download key.
05:29:30 INFO: Registry: Successfully modified WifiSense Open-ness key.
05:29:30 INFO: Registry: Successfully modified WifiSense Credential Share key.
05:29:30 INFO: Registry: Successfully modified ListPin key.
05:29:30 INFO: Registry: Successfully modified FileSync key.
05:29:30 INFO: OneDrive: unable to uninstall
05:29:30 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
05:29:30 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions
05:30:10 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
05:30:10 INFO: ('Windows', 'DESKTOP-D1QMACN', '10', '10.0.10586', 'AMD64', 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel')
05:30:10 INFO: DisableWinTracking version 3.0.1
05:30:50 INFO: Successfully removed app 'getstarted'
05:30:51 INFO: Successfully removed app 'zunevideo'
05:30:51 INFO: Successfully removed app 'skypeapp'
05:30:51 INFO: Successfully removed app 'bingfinance'
05:30:51 INFO: Successfully removed app 'solitairecollection'
05:30:51 INFO: Successfully removed app 'officehub'
05:30:52 INFO: Successfully removed app 'zunemusic'
05:30:52 INFO: Successfully removed app 'xboxapp'
05:30:52 INFO: Successfully removed app 'onenote'
05:30:52 INFO: Successfully removed app 'sway'
05:30:52 INFO: Successfully removed app 'bingsports'
05:30:52 INFO: Successfully removed app 'bingnews'
```

Any idea how can I get updates working?

**Comment by lenisko** [comment]
Seems like it wasn't this script fault at all.
I have dual boot and windows partition wasn't set as active, settings this solved problem.
