### ISSUE TITLE
Failed to clear DiagTrack log

### ISSUE THREAD

**Issue by dmt0** [10se1ucgo/DisableWinTracking#200]
**INFORMATION:**

* Windows Edition (10 Pro):
* Architecture (64bit):

**LOG:**

```python
16:23:59 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
16:23:59 CRITICAL: DiagTrack: Error output:
```

**Comment by dmt0** [comment]
duplicate
