### ISSUE TITLE
4 Log Errors: DigiTrack, Windows Defender, OneDrive

### ISSUE THREAD

**Issue by fredericmohr** [10se1ucgo/DisableWinTracking#214]
**INFORMATION:**
- Windows Edition: Pro (english), Enterprise LTSB (german)
- Architecture: 64Bit (both)
- Options used: (both times the same)

![screenshot_20160802_113241](https://cloud.githubusercontent.com/assets/5955966/17324043/dc2ce234-58a4-11e6-9e07-9b7c39ea70b3.png)

Log has been the same on both machines as well, the Pro edition ran in virtualbox, the LTSB on a Dell XPS 15. I'm not much of a programmer (especially on windows) but if there's anything I can do to help, let me know. It looks like a lot of the issues are duplicates (probably due to the "report an issue" button). 

**0. Dependencies - Not an issue, but might be good to update the docs**
I got the same "msvcr100.dll missing" error as #192 and installing the [ Microsoft Visual C++ 2010 Redistributable Package (x86)](https://www.microsoft.com/de-de/download/details.aspx?id=5555) for my language fixed it.

**1. DiagTrack - could not take ownership of file**

```
11:30:52 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
11:30:53 CRITICAL: DiagTrack: Error output:
```

**2. Windows Defender -  Unable to mody Sample Submission key**

```
11:30:59 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
```

**3. Windows Defender - Unable to mody Spynet key**

```
11:30:59 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
```

**4. OneDrive - unable to uninstall**
Note, OneDrive is still running in systray (not logged in) after a reboot.

```
11:30:59 INFO: OneDrive: unable to uninstall
```

**FULL LOG:**
Here's the full log, in case I missed anything.

``` python
11:30:30 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
11:30:30 INFO: ('Windows', 'DESKTOP-4DQ1RKJ', '10', '10.0.10586', 'AMD64', 'Intel64 Family 6 Model 42 Stepping 7, GenuineIntel')
11:30:30 INFO: DisableWinTracking version 3.0.1
11:30:49 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
11:30:49 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
11:30:50 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
11:30:50 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
11:30:50 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
11:30:50 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
11:30:51 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
11:30:51 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
11:30:51 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
11:30:51 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
11:30:52 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
11:30:52 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
11:30:53 CRITICAL: DiagTrack: Error output:

11:30:59 INFO: Registry: Successfully modified dmwappushsvc key.
11:30:59 INFO: Registry: Successfully modified DiagTrack key.
11:30:59 INFO: Registry: Successfully modified AllowTelemetry key.
11:30:59 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
11:30:59 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
11:30:59 INFO: Registry: Successfully modified Windows Defender Delivery Optimization Download key.
11:30:59 INFO: Registry: Successfully modified WifiSense Open-ness key.
11:30:59 INFO: Registry: Successfully modified WifiSense Credential Share key.
11:30:59 INFO: Registry: Successfully modified ListPin key.
11:30:59 INFO: Registry: Successfully modified FileSync key.
11:30:59 INFO: OneDrive: unable to uninstall
11:30:59 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
11:30:59 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions
```

**Comment by fredericmohr** [comment]
FYI, I don't know how you try to uninstall OneDrive, but this worked for me (manually executed). Maybe the program can use this approach instead.

```
echo "Disabling use of OneDrive in Windows 10"
New-Property -Path "HKLM:\Software\Policies\Microsoft\Windows\OneDrive" -ItemType Directory -Force >$null
New-PropertyItem -Path "HKLM:\Software\Policies\Microsoft\Windows\OneDrive" -name "DisableFileSyncNGSC" -Type DWORD -value 1 -Force >$null

echo "Stopping OneDrive"
taskkill /f /im OneDrive.exe

echo "Uninstalling OneDrive"
%SystemRoot%\SysWOW64\OneDriveSetup.exe /uninstall
```

**Comment by fredericmohr** [comment]
Another info, following the tutorial on https://fix10.isleaked.com, I assume that the following is what should theoretically fix the DiagTrack issue.

```
# worked on LTSB (Pro ed. said "service not found")
sc delete DiagTrack
# both editions said "service not found" for this service
sc delete dmwappushservice
# worked on LTSB, Pro ed. said "Access Denied" (can't overwrite, it seems another app is using the file)
echo "" > C:\ProgramData\Microsoft\Diagnosis\ETLLogs\AutoLogger\AutoLogger-Diagtrack-Listener.etl
# worked on both editions. 
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection" /v AllowTelemetry /t REG_DWORD /d 0 /f`
```

Maybe this'll help you with debugging the issues listed above.
