### ISSUE TITLE
Services were deleted unexpectedly and local searched stopped working

### ISSUE THREAD

**Issue by rodgerkeesee** [10se1ucgo/DisableWinTracking#217]
**INFORMATION:**
- Windows Edition (Home/Pro/Enterprise): Windows 10 Pro clean install to a new HDD
- Architecture (32bit/64bit): 64 bit
- Options used: All Windows 10 settings were default before running this tool. I checked all boxes except "even more tracking domains". None of the Built-in Apps boxes are checked. Service Method = Disable because this was a test and I expected to be able to undo the changes. 

Problem: 
Both services were REMOVED and I cannot undo the changes.

Local Search from the start menu does not work. No results are returned no matter what is searched. Cortana is enabled. The start menu says "We can't connect to web search right now but you can still search your stuff. Make sure you are currently connected to the Internet." So I assumed it was hosts file. Reverting hosts file back to default did not fix the problem. 

The problem with local search was fixed be enabling outbound traffic to 204.79.197.200.

**LOG:**

``` python
09:06:27 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
09:06:27 INFO: ('Windows', 'ULTRON', '10', '10.0.10586', 'AMD64', 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
09:06:27 INFO: DisableWinTracking version 3.0.1
09:18:29 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
09:18:29 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
09:18:29 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
09:18:29 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
09:18:29 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
09:18:29 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
09:18:29 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
09:18:29 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
09:18:29 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
09:18:29 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
09:18:29 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
09:18:29 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
09:18:29 CRITICAL: DiagTrack: Error output:

09:18:29 INFO: Services: Succesfully removed service 'dmwappushsvc'
09:18:29 INFO: Services: Succesfully removed service 'DiagTrack'
09:18:29 INFO: Registry: Successfully modified dmwappushsvc key.
09:18:29 INFO: Registry: Successfully modified DiagTrack key.
09:18:29 INFO: Registry: Successfully modified AllowTelemetry key.
09:18:29 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
09:18:29 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
09:18:29 INFO: Registry: Successfully modified Windows Defender Delivery Optimization Download key.
09:18:29 INFO: Registry: Successfully modified WifiSense Open-ness key.
09:18:29 INFO: Registry: Successfully modified WifiSense Credential Share key.
09:18:29 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
09:18:29 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions
```

**Comment by rodgerkeesee** [comment]
I was able to restore the local search capability be disabling all the firewall outbound-block rules and restarting the PC. If I determine precisely what IP caused the problem I will post it here. The problem about the services being removed, instead of disabled, is still a problem.
