### ISSUE TITLE
DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file

### ISSUE THREAD

**Issue by gooodmorningopenstack** [10se1ucgo/DisableWinTracking#222]
**INFORMATION:**
- Windows Edition (Home/Pro/Enterprise): Pro
- Architecture (32bit/64bit): 64bits
- Options used: clear_diagtrack

**LOG:**

```
02:37:23 INFO: Successfully removed app 'windowscamera'
02:37:25 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
02:37:25 CRITICAL: DiagTrack: Error output:

02:37:25 INFO: Services: Succesfully removed service 'dmwappushsvc'
```

**Comment by gooodmorningopenstack** [comment]
Following the 1607 build update, but this may be not related.
The error appears on two of two updated hosts.

**Comment by dack** [comment]
On my 1607 system, the file just did not exist (the AutoLogger folder was empty).

**Comment by gooodmorningopenstack** [comment]
For me, AutoLogger-Diagtrack-Listener.etl exists in the path and is owned by Administrators group with full NTFS rights.

**Comment by Atavic** [comment]
Full of similar reports!
