### ISSUE TITLE
W10x64 ENT v1607 (BUILD 14393.51) - Windows Defender ERRORs

### ISSUE THREAD

**Issue by rideekulous** [10se1ucgo/DisableWinTracking#223]
**INFORMATION:**
- Windows Edition (Home/Pro/Enterprise): 10 Enterprise
- Architecture (32bit/64bit): 64
- Options used: All

**LOG:**

``` python
14:33:21 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
14:33:21 INFO: ('Windows', 'RDKLS-AORUS-W10', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 70 Stepping 1, GenuineIntel')
14:33:21 INFO: DisableWinTracking version 3.0.1
14:34:19 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
14:34:19 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
14:34:19 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
14:34:19 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
14:34:19 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
14:34:19 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
14:34:19 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
14:34:19 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
14:34:19 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
14:34:20 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
14:34:20 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
14:34:20 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
14:34:20 CRITICAL: DiagTrack: Error output:

14:34:20 INFO: Services: Succesfully removed service 'dmwappushsvc'
14:34:20 INFO: Services: Succesfully removed service 'DiagTrack'
14:34:20 INFO: Registry: Successfully modified dmwappushsvc key.
14:34:20 INFO: Registry: Successfully modified DiagTrack key.
14:34:20 INFO: Registry: Successfully modified AllowTelemetry key.
14:34:20 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
14:34:20 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
14:34:20 INFO: Registry: Successfully modified Windows Defender Delivery Optimization Download key.
14:34:20 INFO: Registry: Successfully modified WifiSense Open-ness key.
14:34:20 INFO: Registry: Successfully modified WifiSense Credential Share key.
14:34:20 INFO: Registry: Successfully modified ListPin key.
14:34:20 INFO: Registry: Successfully modified FileSync key.
14:34:20 INFO: OneDrive: unable to uninstall
14:34:20 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
14:34:20 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions

```

**Comment by rideekulous** [comment]
Ran again...

14:40:34 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
14:40:34 INFO: ('Windows', 'RDKLS-AORUS-W10', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 70 Stepping 1, GenuineIntel')
14:40:34 INFO: DisableWinTracking version 3.0.1
14:40:48 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
14:40:48 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
14:40:49 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
14:40:49 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
14:40:49 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
14:40:49 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
14:40:49 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
14:40:49 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
14:40:49 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
14:40:49 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
14:40:49 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
14:40:49 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
14:40:49 CRITICAL: DiagTrack: Error output:

14:40:50 ERROR: Services: Failed to remove service 'DiagTrack'
Traceback (most recent call last):
  File "dwt_util.py", line 109, in delete_service
  File "site-packages\win32\lib\win32serviceutil.py", line 303, in RemoveService
error: (1072, 'DeleteService', 'The specified service has been marked for deletion.')
14:40:50 INFO: Registry: Successfully modified dmwappushsvc key.
14:40:50 INFO: Registry: Successfully modified DiagTrack key.
14:40:50 INFO: Registry: Successfully modified AllowTelemetry key.
14:40:50 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
14:40:50 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
14:40:50 INFO: Registry: Successfully modified Windows Defender Delivery Optimization Download key.
14:40:50 INFO: Registry: Successfully modified WifiSense Open-ness key.
14:40:50 INFO: Registry: Successfully modified WifiSense Credential Share key.
14:40:50 INFO: Registry: Successfully modified ListPin key.
14:40:50 INFO: Registry: Successfully modified FileSync key.
14:40:50 INFO: OneDrive: unable to uninstall
14:40:50 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
14:40:50 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions
