### ISSUE TITLE
Issue on win10x64

### ISSUE THREAD

**Issue by desmond810508** [10se1ucgo/DisableWinTracking#237]
**INFORMATION:**
- Windows Edition (Home/Pro/Enterprise):
- Architecture (32bit/64bit):
- Options used:

**LOG:**

``` python
08:51:13 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
08:51:13 INFO: ('Windows', 'DESKTOP-MAMLGJR', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
08:51:13 INFO: DisableWinTracking version 3.0.1
08:51:58 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
08:51:58 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
08:51:58 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
08:51:58 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
08:51:58 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
08:51:58 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
08:51:58 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
08:51:58 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
08:51:58 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
08:51:59 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
08:51:59 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
08:51:59 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
08:51:59 CRITICAL: DiagTrack: Error output:

08:51:59 INFO: Services: Succesfully removed service 'dmwappushsvc'
08:51:59 INFO: Services: Succesfully removed service 'DiagTrack'
08:51:59 INFO: Registry: Successfully modified dmwappushsvc key.
08:51:59 INFO: Registry: Successfully modified DiagTrack key.
08:51:59 INFO: Registry: Successfully modified AllowTelemetry key.
08:51:59 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] 
08:51:59 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] 
08:51:59 INFO: Registry: Successfully modified Windows Defender Delivery Optimization Download key.
08:51:59 INFO: Registry: Successfully modified WifiSense Open-ness key.
08:51:59 INFO: Registry: Successfully modified WifiSense Credential Share key.
08:51:59 INFO: Registry: Successfully modified ListPin key.
08:51:59 INFO: Registry: Successfully modified FileSync key.
08:51:59 INFO: OneDrive: unable to uninstall
08:51:59 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
08:51:59 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions
08:56:01 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
08:56:01 INFO: ('Windows', 'DESKTOP-MAMLGJR', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
08:56:01 INFO: DisableWinTracking version 3.0.1
08:56:48 INFO: Successfully removed app 'getstarted'
08:56:48 INFO: Successfully removed app 'bingnews'
08:56:57 INFO: Successfully removed app 'zunevideo'
08:56:57 INFO: Successfully removed app 'windowsphone'
08:56:57 INFO: Successfully removed app 'skypeapp'
08:56:57 INFO: Successfully removed app 'bingfinance'
08:56:59 INFO: Successfully removed app 'solitairecollection'
08:56:59 INFO: Successfully removed app 'officehub'
08:57:06 INFO: Successfully removed app 'bingweather'
08:57:06 INFO: Successfully removed app 'zunemusic'
08:57:06 INFO: Successfully removed app 'photos'
08:57:06 INFO: Successfully removed app '3dbuilder'
08:57:06 INFO: Successfully removed app 'xboxapp'
08:57:06 INFO: Successfully removed app 'soundrecorder'
08:57:06 INFO: Successfully removed app 'onenote'
08:57:06 INFO: Successfully removed app 'windowscommunicationsapps'
08:57:06 INFO: Successfully removed app 'windowsmaps'
08:57:06 INFO: Successfully removed app 'sway'
08:57:06 INFO: Successfully removed app 'bingsports'
08:57:06 INFO: Successfully removed app 'people'
08:57:06 INFO: Successfully removed app 'windowscamera'
09:07:41 INFO: Registry: Successfully modified ListPin key.
09:07:41 INFO: Registry: Successfully modified FileSync key.
09:07:41 INFO: OneDrive: unable to uninstall
09:07:41 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
09:07:41 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions
09:07:53 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
09:07:53 INFO: ('Windows', 'DESKTOP-MAMLGJR', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
09:07:53 INFO: DisableWinTracking version 3.0.1
09:08:06 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] 
09:08:06 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] 
09:08:06 INFO: Registry: Successfully modified Windows Defender Delivery Optimization Download key.
09:08:06 INFO: Registry: Successfully modified WifiSense Open-ness key.
09:08:06 INFO: Registry: Successfully modified WifiSense Credential Share key.
09:08:06 INFO: Registry: Successfully modified ListPin key.
09:08:06 INFO: Registry: Successfully modified FileSync key.
09:08:06 INFO: OneDrive: unable to uninstall
09:08:06 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
09:08:06 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions
09:11:40 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
09:11:40 INFO: ('Windows', 'DESKTOP-MAMLGJR', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
09:11:40 INFO: DisableWinTracking version 3.0.1
09:11:50 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] 
09:11:50 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] 
09:11:50 INFO: Registry: Successfully modified Windows Defender Delivery Optimization Download key.
09:11:50 INFO: Registry: Successfully modified WifiSense Open-ness key.
09:11:50 INFO: Registry: Successfully modified WifiSense Credential Share key.
09:11:50 INFO: Registry: Successfully modified ListPin key.
09:11:50 INFO: Registry: Successfully modified FileSync key.
09:11:50 INFO: OneDrive: unable to uninstall
09:11:50 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
09:11:50 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions
```

**Comment by Atavic** [comment]
`ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last)` appears in a lot of reports.

For Windows Defender, have you stopped it before running DWT?
