### ISSUE TITLE
Your DWT has viruses (see attached screenshot)

### ISSUE THREAD

**Issue by ecornel** [10se1ucgo/DisableWinTracking#250]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
09:18:25 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
09:18:26 INFO: ('Windows', 'DESKTOP-5CN7S1M', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
09:18:26 INFO: DisableWinTracking version 3.0.1
09:22:10 INFO: Successfully removed app 'getstarted'
09:22:10 INFO: Successfully removed app 'windowsphone'
09:22:15 INFO: Successfully removed app 'bingweather'
09:22:15 INFO: Successfully removed app 'skypeapp'
09:22:15 INFO: Successfully removed app 'bingfinance'
09:22:15 INFO: Successfully removed app 'officehub'
09:22:15 INFO: Successfully removed app 'zunemusic'
09:22:15 INFO: Successfully removed app '3dbuilder'
09:22:20 INFO: Successfully removed app 'xboxapp'
09:22:20 INFO: Successfully removed app 'soundrecorder'
09:22:20 INFO: Successfully removed app 'onenote'
09:22:20 INFO: Successfully removed app 'windowscommunicationsapps'
09:22:20 INFO: Successfully removed app 'windowsmaps'
09:22:20 INFO: Successfully removed app 'bingsports'
09:22:20 INFO: Successfully removed app 'people'
09:22:20 INFO: Successfully removed app 'bingnews'
09:24:01 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
09:24:01 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
09:24:01 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
09:24:01 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
09:24:01 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
09:24:02 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
09:24:02 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
09:24:02 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
09:24:02 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
09:24:02 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
09:24:02 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
09:24:02 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
09:24:02 CRITICAL: DiagTrack: Error output:

09:24:02 INFO: Services: Succesfully removed service 'dmwappushsvc'
09:24:02 INFO: Services: Succesfully removed service 'DiagTrack'
09:24:02 INFO: Registry: Successfully modified dmwappushsvc key.
09:24:02 INFO: Registry: Successfully modified DiagTrack key.
09:24:02 INFO: Registry: Successfully modified AllowTelemetry key.
09:24:04 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
09:24:04 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
09:24:04 INFO: Registry: Successfully modified Windows Defender Delivery Optimization Download key.
09:24:04 INFO: Registry: Successfully modified ListPin key.
09:24:04 INFO: Registry: Successfully modified FileSync key.
09:24:04 INFO: OneDrive: unable to uninstall
09:24:04 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
09:24:04 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions
![dwt_has_virus](https://cloud.githubusercontent.com/assets/13018515/20236360/ac3da2c8-a8ba-11e6-888b-104952140d55.jpg)

```

**Comment by TheNain38** [comment]
Some viruses modifies the: "hosts" files, to prevent you from accessing websites like: "virustotal.com" etc... and BitDefender think that because it has been modified (By DWT to prevent Windows from accessing his DNS addresses), it thinks you're infected

**Comment by ecornel** [comment]
Got it. I thought about it your way, too. Bitdefender just thinks it is a
virus, but surely is not. Bitdefender immediately said that it "cleansed"
the "virus". After installing and using DWT, I restarted my PC and there
was no problem. Thanks for this great tool. Be blessed. Eugen

**Comment by richsketchy** [comment]
Who is this please


richsketchy@aim.com



-----Original Message-----

**Comment by ecornel** [comment]
Hi, i'm Eugen from Bucharest and i've already resolved my issue. Somebody
on the project answered to my questions.
Thanks,
Eugen
