### ISSUE TITLE
Why does it require dns? Is it calling home?

### ISSUE THREAD

**Issue by trendzetter** [10se1ucgo/DisableWinTracking#260]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
10:35:24 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
10:35:24 INFO: ('Windows', 'DESKTOP-8UL9CEV', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')
10:35:24 INFO: DisableWinTracking version 3.0.1
10:35:24 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 440, in <module>
  File "dwt_about.py", line 170, in update_check
  File "urllib2.py", line 154, in urlopen
  File "urllib2.py", line 431, in open
  File "urllib2.py", line 449, in _open
  File "urllib2.py", line 409, in _call_chain
  File "urllib2.py", line 1240, in https_open
  File "urllib2.py", line 1197, in do_open
URLError: <urlopen error [Errno 11001] getaddrinfo failed>
```

**Comment by 10se1ucgo** [comment]
Yes, DWT, software for privacy, in fact steals all of your precious cookies and passwords, sending them to my mainframe database. As we speak, I am currently hacking into your bank account and draining it off all your money. 

No, it's just an update checker.

**Comment by Therianulf** [comment]
I think its safe to close this one.
