### ISSUE TITLE
Some errors occured

### ISSUE THREAD

**Issue by kent1325** [10se1ucgo/DisableWinTracking#273]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Pro
* Architecture (32bit/64bit): 64bit
* Options used: Runned the program as admin -> Service method = disable -> Mode = privacy -> All check boxes checked except built in aps and uninstall Onedrive

**LOG:**
```python
09:57:47 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
09:57:47 INFO: ('Windows', 'KentsPC', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
09:57:47 INFO: DisableWinTracking version 3.0.1
09:58:30 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
09:58:30 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
09:58:30 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
09:58:30 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
09:58:30 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
09:58:30 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
09:58:30 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
09:58:30 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
09:58:31 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
09:58:31 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
09:58:31 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
09:58:31 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
09:58:31 CRITICAL: DiagTrack: Error output:

09:58:31 INFO: Services: Succesfully removed service 'dmwappushsvc'
09:58:31 INFO: Services: Succesfully removed service 'DiagTrack'
09:58:31 INFO: Registry: Successfully modified dmwappushsvc key.
09:58:31 INFO: Registry: Successfully modified DiagTrack key.
09:58:31 INFO: Registry: Successfully modified AllowTelemetry key.
09:58:31 ERROR: Hosts: Failed to modify hosts file
Traceback (most recent call last):
  File "dwt_util.py", line 231, in host_file
IOError: [Errno 13] Permission denied: 'C:\\WINDOWS\\System32/drivers/etc/hosts'
09:58:31 ERROR: Hosts: Failed to modify hosts file
Traceback (most recent call last):
  File "dwt_util.py", line 231, in host_file
IOError: [Errno 13] Permission denied: 'C:\\WINDOWS\\System32/drivers/etc/hosts'
09:58:31 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
09:58:31 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
09:58:31 INFO: Registry: Successfully modified Windows Defender Delivery Optimization Download key.
09:58:31 INFO: Registry: Successfully modified WifiSense Open-ness key.
09:58:31 INFO: Registry: Successfully modified WifiSense Credential Share key.
09:58:31 INFO: Registry: Successfully modified ListPin key.
09:58:31 INFO: Registry: Successfully modified FileSync key.
09:58:31 INFO: OneDrive: unable to uninstall
09:58:31 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
09:58:31 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions
09:59:17 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
09:59:17 INFO: ('Windows', 'KentsPC', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
09:59:17 INFO: DisableWinTracking version 3.0.1
09:59:27 INFO: Registry: Successfully modified ListPin key.
09:59:27 INFO: Registry: Successfully modified FileSync key.
09:59:27 INFO: OneDrive: unable to uninstall
09:59:27 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
09:59:27 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions
10:03:13 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
10:03:13 INFO: ('Windows', 'KentsPC', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
10:03:13 INFO: DisableWinTracking version 3.0.1
10:03:27 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
10:03:27 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
10:03:28 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
10:03:28 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
10:03:28 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
10:03:28 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
10:03:28 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
10:03:28 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
10:03:28 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
10:03:28 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
10:03:28 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
10:03:28 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
10:03:28 CRITICAL: DiagTrack: Error output:

10:03:28 INFO: Registry: Successfully modified dmwappushsvc key.
10:03:28 INFO: Registry: Successfully modified DiagTrack key.
10:03:28 INFO: Registry: Successfully modified AllowTelemetry key.
10:03:28 ERROR: Hosts: Failed to modify hosts file
Traceback (most recent call last):
  File "dwt_util.py", line 231, in host_file
IOError: [Errno 13] Permission denied: 'C:\\WINDOWS\\System32/drivers/etc/hosts'
10:03:28 ERROR: Hosts: Failed to modify hosts file
Traceback (most recent call last):
  File "dwt_util.py", line 231, in host_file
IOError: [Errno 13] Permission denied: 'C:\\WINDOWS\\System32/drivers/etc/hosts'
10:03:28 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
10:03:28 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
10:03:28 INFO: Registry: Successfully modified Windows Defender Delivery Optimization Download key.
10:03:28 INFO: Registry: Successfully modified WifiSense Open-ness key.
10:03:28 INFO: Registry: Successfully modified WifiSense Credential Share key.
10:03:28 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
10:03:28 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions

```

**Comment by Didey** [comment]
"Could not take ownership of file"
"Access is denied"
Did you run the program as admin? Are you in some kind of admin-controlled account? Do you have admin privileges?

**Comment by kent1325** [comment]
Yes i am 100% positive that i did run it as an admin.
It is a office computer and the user i use to login in with is a domain user with ofcourse some group policies. But i know for sure that i am under the admin groups so it shouldnt affect me.
