### ISSUE TITLE
idk some stuff didnt work

### ISSUE THREAD

**Issue by ghost** [10se1ucgo/DisableWinTracking#289]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
00:11:35 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
00:11:35 INFO: ('Windows', 'Surface', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 69 Stepping 1, GenuineIntel')
00:11:35 INFO: DisableWinTracking version 3.0.1
00:11:59 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 258, in hosts_warn
AttributeError: 'CommandEvent' object has no attribute 'GetObject'

00:13:15 INFO: Successfully removed app 'getstarted'
00:13:15 INFO: Successfully removed app 'bingnews'
00:13:15 INFO: Successfully removed app 'windowsphone'
00:13:15 INFO: Successfully removed app 'skypeapp'
00:13:15 INFO: Successfully removed app 'bingfinance'
00:13:15 INFO: Successfully removed app 'solitairecollection'
00:13:15 INFO: Successfully removed app 'officehub'
00:13:15 INFO: Successfully removed app 'bingweather'
00:13:15 INFO: Successfully removed app 'zunevideo'
00:13:15 INFO: Successfully removed app '3dbuilder'
00:13:15 INFO: Successfully removed app 'xboxapp'
00:13:15 INFO: Successfully removed app 'soundrecorder'
00:13:15 INFO: Successfully removed app 'onenote'
00:13:15 INFO: Successfully removed app 'windowscommunicationsapps'
00:13:15 INFO: Successfully removed app 'windowsmaps'
00:13:15 INFO: Successfully removed app 'sway'
00:13:15 INFO: Successfully removed app 'bingsports'
00:13:15 INFO: Successfully removed app 'people'
00:13:15 INFO: Successfully removed app 'windowscamera'
00:13:17 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
00:13:17 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
00:13:18 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
00:13:18 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
00:13:18 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
00:13:18 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
00:13:18 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
00:13:18 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
00:13:18 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
00:13:18 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
00:13:18 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
00:13:19 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
00:13:19 CRITICAL: DiagTrack: Error output:

00:13:19 INFO: Services: Succesfully removed service 'dmwappushsvc'
00:13:19 INFO: Services: Succesfully removed service 'DiagTrack'
00:13:19 INFO: Registry: Successfully modified dmwappushsvc key.
00:13:19 INFO: Registry: Successfully modified DiagTrack key.
00:13:19 INFO: Registry: Successfully modified AllowTelemetry key.
00:13:19 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Acesso negado
00:13:19 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Acesso negado
00:13:19 INFO: Registry: Successfully modified Windows Defender Delivery Optimization Download key.
00:13:19 INFO: Registry: Successfully modified WifiSense Open-ness key.
00:13:19 INFO: Registry: Successfully modified WifiSense Credential Share key.
00:13:19 INFO: Registry: Successfully modified ListPin key.
00:13:19 INFO: Registry: Successfully modified FileSync key.
00:13:19 INFO: OneDrive: unable to uninstall
00:13:19 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
00:13:19 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions

```

**Comment by Konng** [comment]
This was on a fresh install of W1

**Comment by Didey** [comment]
I don't speak much Spanish(or whatever language this is) but I'm gonna go ahead and assume

> WindowsError: [Error 5] Acesso negado

Means that you didn't run the program as admin. Try again, running as admin.
