### ISSUE TITLE
Failed to clear DiagTrack log

### ISSUE THREAD

**Issue by Daevor** [10se1ucgo/DisableWinTracking#293]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**Because the file doesn't exist.**

**LOG:**

```python
20:08:15 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
20:08:15 INFO: ('Windows', 'DESKTOP-8JIKF3P', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 70 Stepping 1, GenuineIntel')
20:08:15 INFO: DisableWinTracking version 3.0.1
20:10:01 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
20:10:01 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
20:10:02 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
20:10:02 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
20:10:02 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
20:10:03 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
20:10:03 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
20:10:04 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
20:10:04 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
20:10:05 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
20:10:06 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
20:10:06 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
20:10:06 CRITICAL: DiagTrack: Error output:

20:10:06 INFO: Services: Succesfully removed service 'dmwappushsvc'
20:10:06 INFO: Services: Succesfully removed service 'DiagTrack'
20:10:06 INFO: Registry: Successfully modified dmwappushsvc key.
20:10:06 INFO: Registry: Successfully modified DiagTrack key.
20:10:06 INFO: Registry: Successfully modified AllowTelemetry key.
20:10:06 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
20:10:06 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions

```

**Comment by GiveMeAnthony** [comment]
I'm having this issue as well as issues with the Windows Defender collection. I even went and manually added Administrators as owners. Something is strange here, maybe it has to do with the anniversary update? I was able to remove the log from Powershell after taking ownership though. So, for now, I'm just going to remove that file at the end of every session.

**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
19:13:07 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
19:13:07 INFO: ('Windows', 'DESKTOP-QH2BV16', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 61 Stepping 4, GenuineIntel')
19:13:07 INFO: DisableWinTracking version 3.0.1
19:13:25 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
19:13:25 CRITICAL: DiagTrack: Error output:

19:13:25 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
19:13:25 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
19:13:25 INFO: Registry: Successfully modified Windows Defender Delivery Optimization Download key.
19:13:25 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
19:13:25 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions
```q
