### ISSUE TITLE
DiagTrack Listener Log Error

### ISSUE THREAD

**Issue by Ruined1** [10se1ucgo/DisableWinTracking#313]
**INFORMATION:**

* Windows Edition 10 Pro
* Architecture x64
* Options used: All

**LOG:**

`17:10:32 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
17:10:32 CRITICAL: DiagTrack: Error output:`

Able to `takeown /f "C:\ProgramData\Microsoft\Diagnosis\ETLLogs\AutoLogger\AutoLogger-Diagtrack-Listener.etl"` from command prompt just fine. Has to be issue with the call to subprocess in dwt_util.py

This isn't a huge issue as most people running this will be on a fresh install of windows, but it's a bug none the less.

**Comment by Ruined1** [comment]
Able to perform both command just fine from the command prompt, so I don't think the non-zero status is necessarily an error, going to test this and see and re-work the way it's perceived if so.

**Comment by Ruined1** [comment]
Yup, logged all three commands as they were being pushed by DWT and then manually used the commands line-by-line. Everything works perfectly, so the errors in the log are just returned information being inncorrectly handled as errors.

`C:\Windows\system32>takeown /f C:\ProgramData\Microsoft\Diagnosis\ETLLogs\AutoLogger\AutoLogger-Diagtrack-Listener.etl

SUCCESS: The file (or folder): "C:\ProgramData\Microsoft\Diagnosis\ETLLogs\AutoLogger\AutoLogger-Diagtrack-Listener.etl" now owned by user "WINBOX-D\Winbox".

C:\Windows\system32>icacls C:\ProgramData\Microsoft\Diagnosis\ETLLogs\AutoLogger\AutoLogger-Diagtrack-Listener.etl /grant administrators:F
processed file: C:\ProgramData\Microsoft\Diagnosis\ETLLogs\AutoLogger\AutoLogger-Diagtrack-Listener.etl
Successfully processed 1 files; Failed processing 0 files

C:\Windows\system32>echo y | cacls C:\ProgramData\Microsoft\Diagnosis\ETLLogs\AutoLogger\AutoLogger-Diagtrack-Listener.etl /d SYSTEM
Are you sure (Y/N)?
C:\Windows\system32>`

**Comment by Ruined1** [comment]
After changing some code to log the subprocess output, it is, in fact, failing:

```
ERROR: The system cannot find the file specified.
20:27:12 INFO:
20:27:12 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
```

```
20:27:12 INFO: Successfully processed 0 files; Failed processing 1 files

20:27:12 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not grant administrator permissions to file
Traceback (most recent call last):
```

This file is hidden from our commands, likely due to missing privileges of the subprocess.

**Comment by Ruined1** [comment]
# Update
wrote a simple program test.py:

```
import os
import subprocess

file = os.path.join(os.environ['SYSTEMDRIVE'], ('\\ProgramData\\Microsoft\\Diagnosis\\ETLLogs\\AutoLogger\\AutoLogger-Diagtrack-Listener.etl'))
print file

own_cmd = "takeown /f {file}".format(file=file)
print own_cmd

p = subprocess.Popen(own_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)
output = p.communicate()
print output

if p.returncode:
	print p.returncode.decode()
	raise CalledProcessError(returncode=p.returncode, cmd=cmd, output=output[0], stderr=output[1])
```

that outputs

```
C:\Windows\system32>python c:\dwt\DisableWinTracking\test.py
C:\ProgramData\Microsoft\Diagnosis\ETLLogs\AutoLogger\AutoLogger-Diagtrack-Listener.etl
takeown /f C:\ProgramData\Microsoft\Diagnosis\ETLLogs\AutoLogger\AutoLogger-Diagtrack-Listener.etl
('\r\nSUCCESS: The file (or folder): "C:\\ProgramData\\Microsoft\\Diagnosis\\ETLLogs\\AutoLogger\\AutoLogger-Diagtrack-Listener.etl" now owned by user "WINBOX-D\\Winbox".\r\n', '')
```

so everything should work just fine, but doesn't... gotta be a typo in DWT somewhere... Still working on it.

**Comment by Ruined1** [comment]
Solved with rewrite of clear_diagtrack() in dwt_util.py.

It's ugly as sin, and it doesn't take "advantage" of subprocess_handler(), but on the flip side... It actually works... I tried EVERYTHING to get it to work with subprocess_handler() first, to be fair...
