### ISSUE TITLE
Unable to uninstall OneDrive / Failed to remove service 'DiagTrack'

### ISSUE THREAD

**Issue by A-Casual-Guy** [10se1ucgo/DisableWinTracking#333]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Windows 10 Home;
* Architecture: 64 bit;
* Options used: All options + disable.

**LOG:**

```python
16:20:11 ERROR: 1332
None
16:20:11 INFO: DiagTrack: Successfully cleared and locked DiagTrack log.
16:20:11 ERROR: Services: Failed to remove service 'DiagTrack'
Traceback (most recent call last):
  File "dwt_util.py", line 122, in delete_service
  File "site-packages\win32\lib\win32serviceutil.py", line 303, in RemoveService
error: (1072, 'DeleteService', 'Określona usługa została oznaczona do usunięcia.')
16:20:11 INFO: Registry: Successfully modified dmwappushsvc key.
16:20:11 INFO: Registry: Successfully modified DiagTrack key.
16:20:11 INFO: Registry: Successfully modified AllowTelemetry key.
16:20:11 INFO: Registry: Successfully modified WifiSense Open-ness key.
16:20:11 INFO: Registry: Successfully modified WifiSense Credential Share key.
16:20:11 INFO: Registry: Successfully modified ListPin key.
16:20:11 INFO: Registry: Successfully modified FileSync key.
16:20:11 INFO: OneDrive: unable to uninstall
16:20:11 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
16:20:11 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions
```
(Note: some of the text may be Polish [as I'm using Polish lang, duh].)

**Comment by Ruined1** [comment]
DiagTrack fixed in version 3.1.3
unable to uninstall one drive because you probably already did
