### ISSUE TITLE
Unable to mody Windows Defender Sample Submission key.

### ISSUE THREAD

**Issue by ethanbin** [10se1ucgo/DisableWinTracking#334]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
11:40:23 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
11:40:23 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
11:40:23 INFO: Registry: Successfully modified Windows Defender Delivery Optimization Download key.
```

**Comment by ethanbin** [comment]
Note: antivirus was disabled during this time.

**Comment by Ruined1** [comment]
I don't know what old version you were using, but this feature was disabled already as it was a limitation of windows. Not only than but this issue is completely unformatted with a partial log.
