### ISSUE TITLE
Can't run if path contain Cyrillic folder name

### ISSUE THREAD

**Issue by N0xFF** [10se1ucgo/DisableWinTracking#342]
```
C:\>"D:\Software\Системные\DisableWinTracking.exe"
Traceback (most recent call last):
  File "dwt.py", line 482, in <module>
  File "dwt.py", line 94, in __init__
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd1 in position 12: invalid continuation byte
Failed to execute script dwt
```
D:\Software\ **Системные** \DisableWinTracking.exe

Meanwhile, my old file **Disable Windows 10 Tracking v2.5.1** works fine.

Windows 10 Pro x64

**Comment by piranhaeatmeat** [comment]
I have a same issue on version 3.1.2.

**Comment by Ruined1** [comment]
Run it from the root folder of the drive.
D:\DisableWinTracking.exe
