### ISSUE TITLE
Services not being disabled properly

### ISSUE THREAD

**Issue by AdamMcAdamson** [10se1ucgo/DisableWinTracking#344]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Pro
* Architecture (32bit/64bit): 64-bit
* Options used: Services, (All Others Except Uninstall OneDrive), Disable, Privacy

svchost.exe (netsvcs) is (still) using 20+Mbps after running, restarting, and re-running.

**LOG:**

```python
14:30:56 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
14:30:56 INFO: ('Windows', 'DESKTOP-6B3NQP8', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
14:30:56 INFO: DisableWinTracking version 3.1.2
14:32:27 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
14:32:27 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
14:32:27 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
14:32:27 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
14:32:27 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
14:32:27 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
14:32:28 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
14:32:28 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
14:32:28 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
14:32:28 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
14:32:28 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
14:32:28 INFO: DiagTrack: Take Ownership of AutoLogger-Diagtrack-Listener.etl was successful
14:32:28 INFO: DiagTrack: Grant Admin Privilege of AutoLogger-Diagtrack-Listener.etl was successful
14:32:28 INFO: DiagTrack: Cleared AutoLogger-Diagtrack-Listener.etl
14:32:28 INFO: DiagTrack: Deny System Privilege of AutoLogger-Diagtrack-Listener.etl was successful
14:32:28 INFO: DiagTrack: Successfully cleared and locked DiagTrack log.
14:32:28 INFO: Services: Succesfully removed service 'dmwappushsvc'
14:32:28 INFO: Services: Succesfully removed service 'DiagTrack'
14:32:28 INFO: Registry: Successfully modified dmwappushsvc key.
14:32:28 INFO: Registry: Successfully modified DiagTrack key.
14:32:28 INFO: Registry: Successfully modified AllowTelemetry key.
14:32:28 INFO: Registry: Successfully modified WifiSense Open-ness key.
14:32:28 INFO: Registry: Successfully modified WifiSense Credential Share key.
14:32:28 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
14:32:28 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions
14:33:04 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
14:33:04 INFO: ('Windows', 'DESKTOP-6B3NQP8', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
14:33:04 INFO: DisableWinTracking version 3.1.2
14:33:15 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
14:33:15 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
14:33:15 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
14:33:15 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
14:33:15 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
14:33:15 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
14:33:16 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
14:33:16 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
14:33:16 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
14:33:16 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
14:33:16 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
14:33:16 INFO: DiagTrack: Take Ownership of AutoLogger-Diagtrack-Listener.etl was successful
14:33:16 INFO: DiagTrack: Grant Admin Privilege of AutoLogger-Diagtrack-Listener.etl was successful
14:33:16 INFO: DiagTrack: Cleared AutoLogger-Diagtrack-Listener.etl
14:33:16 INFO: DiagTrack: Deny System Privilege of AutoLogger-Diagtrack-Listener.etl was successful
14:33:16 INFO: DiagTrack: Successfully cleared and locked DiagTrack log.
14:33:16 ERROR: Services: Failed to remove service 'DiagTrack'
Traceback (most recent call last):
  File "dwt_util.py", line 122, in delete_service
  File "site-packages\win32\lib\win32serviceutil.py", line 303, in RemoveService
error: (1072, 'DeleteService', 'The specified service has been marked for deletion.')
14:33:16 INFO: Registry: Successfully modified dmwappushsvc key.
14:33:16 INFO: Registry: Successfully modified DiagTrack key.
14:33:16 INFO: Registry: Successfully modified AllowTelemetry key.
14:33:16 INFO: Registry: Successfully modified WifiSense Open-ness key.
14:33:16 INFO: Registry: Successfully modified WifiSense Credential Share key.
14:33:16 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
14:33:16 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions
14:37:18 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
14:37:18 INFO: ('Windows', 'DESKTOP-6B3NQP8', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
14:37:18 INFO: DisableWinTracking version 3.1.2
14:37:41 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
14:37:41 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
14:37:41 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
14:37:41 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
14:37:41 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
14:37:41 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
14:37:41 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
14:37:41 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
14:37:41 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
14:37:41 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
14:37:41 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
14:37:41 INFO: DiagTrack: Take Ownership of AutoLogger-Diagtrack-Listener.etl was successful
14:37:41 INFO: DiagTrack: Grant Admin Privilege of AutoLogger-Diagtrack-Listener.etl was successful
14:37:41 INFO: DiagTrack: Cleared AutoLogger-Diagtrack-Listener.etl
14:37:41 INFO: DiagTrack: Deny System Privilege of AutoLogger-Diagtrack-Listener.etl was successful
14:37:41 INFO: DiagTrack: Successfully cleared and locked DiagTrack log.
14:37:41 INFO: Registry: Successfully modified dmwappushsvc key.
14:37:41 INFO: Registry: Successfully modified DiagTrack key.
14:37:41 INFO: Registry: Successfully modified AllowTelemetry key.
14:37:41 INFO: Registry: Successfully modified WifiSense Open-ness key.
14:37:41 INFO: Registry: Successfully modified WifiSense Credential Share key.
14:37:41 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
14:37:41 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions
```

**Comment by Ruined1** [comment]
Resolved in v3.1.3
