### ISSUE TITLE
 DisableWinTracking is unable to uninstall OneDrive

### ISSUE THREAD

**Issue by miahelyzet** [10se1ucgo/DisableWinTracking#368]
**DisableWinTracking was unable to uninstall OneDrive**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
07:38:56 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
07:38:56 INFO: ('Windows', 'w10-CYZ-1ER164', '10', '10.0.15063', 'AMD64', 'Intel64 Family 6 Model 42 Stepping 7, GenuineIntel')
07:38:56 INFO: DisableWinTracking version 3.1.2
07:39:37 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
07:39:38 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
07:39:38 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
07:39:38 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
07:39:38 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
07:39:38 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
07:39:38 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
07:39:39 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
07:39:39 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
07:39:39 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
07:39:39 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
07:39:39 INFO: DiagTrack: Take Ownership of AutoLogger-Diagtrack-Listener.etl was successful
07:39:39 INFO: DiagTrack: Grant Admin Privilege of AutoLogger-Diagtrack-Listener.etl was successful
07:39:39 ERROR: 1332
None
07:39:39 ERROR: DiagTrack: Couldn't open AutoLogger-Diagtrack-Listener.etl for writing
Traceback (most recent call last):
  File "dwt_util.py", line 105, in clear_diagtrack
IOError: [Errno 13] Permission denied: 'C:\\ProgramData\\Microsoft\\Diagnosis\\ETLLogs\\AutoLogger\\AutoLogger-Diagtrack-Listener.etl'
07:39:39 INFO: DiagTrack: Deny System Privilege of AutoLogger-Diagtrack-Listener.etl was successful
07:39:39 ERROR: 1332
Traceback (most recent call last):
  File "dwt_util.py", line 105, in clear_diagtrack
IOError: [Errno 13] Permission denied: 'C:\\ProgramData\\Microsoft\\Diagnosis\\ETLLogs\\AutoLogger\\AutoLogger-Diagtrack-Listener.etl'
07:39:39 INFO: DiagTrack: Successfully cleared and locked DiagTrack log.
07:39:39 INFO: Registry: Successfully modified dmwappushsvc key.
07:39:39 INFO: Registry: Successfully modified DiagTrack key.
07:39:39 INFO: Registry: Successfully modified AllowTelemetry key.
07:39:39 INFO: Registry: Successfully modified WifiSense Open-ness key.
07:39:39 INFO: Registry: Successfully modified WifiSense Credential Share key.
07:39:39 INFO: Registry: Successfully modified ListPin key.
07:39:39 INFO: Registry: Successfully modified FileSync key.
07:39:39 INFO: OneDrive: unable to uninstall
07:39:39 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
07:39:39 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions

```

**Comment by Ruined1** [comment]
You can get the "unable to uninstall" message if OneDrive has already been uninstalled. Show me where OneDrive has not be uninstalled from this system.

**Comment by Ruined1** [comment]
Please try the [latest release](https://github.com/10se1ucgo/DisableWinTracking/releases/latest) and the issue should be resolved. If you still need help, please create a new issue.
