### ISSUE TITLE
Errors found in log

### ISSUE THREAD

**Issue by aladdin2006** [10se1ucgo/DisableWinTracking#376]
**INFORMATION:**

* Windows Edition (Pro):
* Architecture (32bit):
* Options used:
Services
Clear DiagTrack log
Telemetry
Block tracking domains
Block tracking IP addresses
Uninstall OneDrive
**DWT LOG GENERATED ON FIRST RUN:**

```python
11:47:05 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
11:47:05 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
11:47:05 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
11:47:06 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
11:47:06 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
11:47:06 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
11:47:06 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
11:47:06 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
11:47:06 INFO: DiagTrack: Successfully deleted service 'DiagTrack'
11:47:06 INFO: DiagTrack: Completed Part 1/3
11:47:06 INFO: DiagTrack: Successfully deleted service 'dmwappushservice'
11:47:06 INFO: DiagTrack: Completed Part 2/3
11:47:07 INFO: DiagTrack: Successfully erased tracking log.
11:47:07 INFO: DiagTrack: Completed Part 3/3
11:47:07 INFO: DiagTrack: Completed successfully, without errors.
_**11:47:10 ERROR: Services: Failed to remove service 'DiagTrack'
Traceback (most recent call last):
  File "dwt_util.py", line 166, in delete_service
  File "site-packages\win32\lib\win32serviceutil.py", line 303, in RemoveService
error: (1072, 'DeleteService', 'The specified service has been marked for deletion.')**_
11:47:11 INFO: Registry: Successfully modified dmwappushsvc key.
11:47:11 INFO: Registry: Successfully modified DiagTrack key.
11:47:11 INFO: Registry: Successfully modified AllowTelemetry key.
_**11:47:11 ERROR: Hosts: Failed to modify hosts file
Traceback (most recent call last):
  File "dwt_util.py", line 303, in host_file
IOError: [Errno 13] Permission denied: 'C:\\Windows\\System32/drivers/etc/hosts'**_
11:47:11 INFO: Registry: Successfully modified ListPin key.
11:47:11 INFO: Registry: Successfully modified FileSync key.
11:47:14 INFO: OneDrive: successfully uninstalled
11:47:14 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
11:47:14 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions
11:54:09 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
11:54:09 INFO: ('Windows', 'DESKTOP-5P8CJQ2', '10', '10.0.16299', 'x86', 'x86 Family 18 Model 1 Stepping 0, AuthenticAMD')
11:54:09 INFO: DisableWinTracking version 3.2.0
```
**DWT LOG GENERATED ON SECOND RUN:**
```python
12:03:37 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
12:03:37 INFO: ('Windows', 'DESKTOP-5P8CJQ2', '10', '10.0.16299', 'x86', 'x86 Family 18 Model 1 Stepping 0, AuthenticAMD')
12:03:37 INFO: DisableWinTracking version 3.2.0
12:04:21 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
12:04:21 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
12:04:21 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
12:04:22 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
12:04:22 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
12:04:22 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
12:04:22 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
12:04:22 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
12:04:22 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
12:04:22 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
12:04:23 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
12:04:23 INFO: DiagTrack: DiagTrack service doesn't exist. This is OK, you likely removed it already.
12:04:23 INFO: DiagTrack: Completed Part 1/3
12:04:23 INFO: DiagTrack: dmwappushservice service doesn't exist. This is OK, you likely removed it already.
12:04:23 INFO: DiagTrack: Completed Part 2/3
12:04:23 INFO: DiagTrack: Successfully erased tracking log.
12:04:23 INFO: DiagTrack: Completed Part 3/3
12:04:23 INFO: DiagTrack: Completed successfully, without errors.
12:04:25 INFO: Registry: Successfully modified dmwappushsvc key.
12:04:25 INFO: Registry: Successfully modified DiagTrack key.
12:04:25 INFO: Registry: Successfully modified AllowTelemetry key.
_**12:04:25 ERROR: Hosts: Failed to modify hosts file
Traceback (most recent call last):
  File "dwt_util.py", line 303, in host_file
IOError: [Errno 13] Permission denied: 'C:\\Windows\\System32/drivers/etc/hosts'**_
12:04:25 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
12:04:25 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions
```
Hosts file couldn't be modified. Please fix this issue.

**Comment by Ruined1** [comment]
It's probably your antivirus preventing it. Windows Defender/AVG/Nortan/Avast/Avira/Whatever...
I am unable to reproduce this issue on multiple systems. It's always ended up being antivirus.

**Comment by aladdin2006** [comment]
I tried disabling WinDefender but no change.
Anyways, please write here what should be added in hosts file so I can manually add them.
Thanks.

**Comment by Ruined1** [comment]
```
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost
0.0.0.0 a.ads1.msn.com
0.0.0.0 a.ads2.msads.net
0.0.0.0 a.ads2.msn.com
0.0.0.0 a.rad.msn.com
0.0.0.0 a-0001.a-msedge.net
0.0.0.0 a-0002.a-msedge.net
0.0.0.0 a-0003.a-msedge.net
0.0.0.0 a-0004.a-msedge.net
0.0.0.0 a-0005.a-msedge.net
0.0.0.0 a-0006.a-msedge.net
0.0.0.0 a-0007.a-msedge.net
0.0.0.0 a-0008.a-msedge.net
0.0.0.0 a-0009.a-msedge.net
0.0.0.0 ac3.msn.com
0.0.0.0 ad.doubleclick.net
0.0.0.0 adnexus.net
0.0.0.0 adnxs.com
0.0.0.0 ads.msn.com
0.0.0.0 ads1.msads.net
0.0.0.0 ads1.msn.com
0.0.0.0 aidps.atdmt.com
0.0.0.0 aka-cdn-ns.adtech.de
0.0.0.0 a-msedge.net
0.0.0.0 az361816.vo.msecnd.net
0.0.0.0 az512334.vo.msecnd.net
0.0.0.0 b.ads1.msn.com
0.0.0.0 b.ads2.msads.net
0.0.0.0 b.rad.msn.com
0.0.0.0 bs.serving-sys.com
0.0.0.0 c.atdmt.com
0.0.0.0 c.msn.com
0.0.0.0 cdn.atdmt.com
0.0.0.0 cds26.ams9.msecn.net
0.0.0.0 choice.microsoft.com
0.0.0.0 choice.microsoft.com.nsatc.net
0.0.0.0 compatexchange.cloudapp.net
0.0.0.0 corp.sts.microsoft.com
0.0.0.0 corpext.msitadfs.glbdns2.microsoft.com
0.0.0.0 cs1.wpc.v0cdn.net
0.0.0.0 db3aqu.atdmt.com
0.0.0.0 df.telemetry.microsoft.com
0.0.0.0 diagnostics.support.microsoft.com
0.0.0.0 ec.atdmt.com
0.0.0.0 feedback.microsoft-hohm.com
0.0.0.0 feedback.search.microsoft.com
0.0.0.0 feedback.windows.com
0.0.0.0 flex.msn.com
0.0.0.0 g.msn.com
0.0.0.0 h1.msn.com
0.0.0.0 i1.services.social.microsoft.com
0.0.0.0 i1.services.social.microsoft.com.nsatc.net
0.0.0.0 lb1.www.ms.akadns.net
0.0.0.0 live.rads.msn.com
0.0.0.0 m.adnxs.com
0.0.0.0 msedge.net
0.0.0.0 msftncsi.com
0.0.0.0 msnbot-65-55-108-23.search.msn.com
0.0.0.0 msntest.serving-sys.com
0.0.0.0 oca.telemetry.microsoft.com
0.0.0.0 oca.telemetry.microsoft.com.nsatc.net
0.0.0.0 pre.footprintpredict.com
0.0.0.0 preview.msn.com
0.0.0.0 rad.live.com
0.0.0.0 rad.msn.com
0.0.0.0 redir.metaservices.microsoft.com
0.0.0.0 reports.wes.df.telemetry.microsoft.com
0.0.0.0 schemas.microsoft.akadns.net
0.0.0.0 secure.adnxs.com
0.0.0.0 secure.flashtalking.com
0.0.0.0 services.wes.df.telemetry.microsoft.com
0.0.0.0 settings-sandbox.data.microsoft.com
0.0.0.0 settings-win.data.microsoft.com
0.0.0.0 sls.update.microsoft.com.akadns.net
0.0.0.0 sqm.df.telemetry.microsoft.com
0.0.0.0 sqm.telemetry.microsoft.com
0.0.0.0 sqm.telemetry.microsoft.com.nsatc.net
0.0.0.0 ssw.live.com
0.0.0.0 static.2mdn.net
0.0.0.0 statsfe1.ws.microsoft.com
0.0.0.0 statsfe2.ws.microsoft.com
0.0.0.0 telecommand.telemetry.microsoft.com
0.0.0.0 telecommand.telemetry.microsoft.com.nsatc.net
0.0.0.0 telemetry.appex.bing.net
0.0.0.0 telemetry.microsoft.com
0.0.0.0 telemetry.urs.microsoft.com
0.0.0.0 v10.vortex-win.data.microsoft.com
0.0.0.0 vortex.data.glbdns2.microsoft.com
0.0.0.0 vortex.data.microsoft.com
0.0.0.0 vortex-bn2.metron.live.com.nsatc.net
0.0.0.0 vortex-cy2.metron.live.com.nsatc.net
0.0.0.0 vortex-sandbox.data.microsoft.com
0.0.0.0 vortex-win.data.metron.live.com.nsatc.net
0.0.0.0 vortex-win.data.microsoft.com
0.0.0.0 watson.live.com
0.0.0.0 web.vortex.data.microsoft.com
0.0.0.0 www.msftncsi.com
0.0.0.0 apps.skype.com
0.0.0.0 fe2.update.microsoft.com.akadns.net
0.0.0.0 m.hotmail.com
0.0.0.0 pricelist.skype.com
0.0.0.0 s.gateway.messenger.live.com
0.0.0.0 s0.2mdn.net
0.0.0.0 statsfe2.update.microsoft.com.akadns.net
0.0.0.0 survey.watson.microsoft.com
0.0.0.0 ui.skype.com
0.0.0.0 view.atdmt.com
0.0.0.0 watson.microsoft.com
0.0.0.0 watson.ppe.telemetry.microsoft.com
0.0.0.0 watson.telemetry.microsoft.com
0.0.0.0 watson.telemetry.microsoft.com.nsatc.net
0.0.0.0 wes.df.telemetry.microsoft.com
```

You're welcome.
