### ISSUE TITLE
Failed to remove service 'DiagTrack'

### ISSUE THREAD

**Issue by AnimeAlvin** [10se1ucgo/DisableWinTracking#380]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Enterprise
* Architecture (32bit/64bit): 64bit
* Options used:

**LOG:**

```python
11:21:31 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
11:21:31 INFO: ('Windows', 'S340', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 158 Stepping 9, GenuineIntel')
11:21:31 INFO: DisableWinTracking version 3.2.1
11:22:26 INFO: DiagTrack: Successfully deleted service 'DiagTrack'
11:22:26 INFO: DiagTrack: Completed Part 1/3
11:22:26 INFO: DiagTrack: Successfully deleted service 'dmwappushservice'
11:22:26 INFO: DiagTrack: Completed Part 2/3
11:22:26 INFO: DiagTrack: Successfully erased tracking log.
11:22:26 INFO: DiagTrack: Completed Part 3/3
11:22:26 INFO: DiagTrack: Completed successfully, without errors.
11:22:26 ERROR: Services: Failed to remove service 'DiagTrack'
Traceback (most recent call last):
  File "dwt_util.py", line 168, in delete_service
  File "site-packages\win32\lib\win32serviceutil.py", line 303, in RemoveService
error: (1072, 'DeleteService', 'The specified service has been marked for deletion.')
11:22:27 INFO: Registry: Successfully modified dmwappushsvc key.
11:22:27 INFO: Registry: Successfully modified DiagTrack key.
11:22:27 INFO: Registry: Successfully modified AllowTelemetry key.
11:22:28 INFO: Registry: Successfully modified WifiSense Open-ness key.
11:22:28 INFO: Registry: Successfully modified WifiSense Credential Share key.
11:22:28 INFO: Registry: Successfully modified ListPin key.
11:22:28 INFO: Registry: Successfully modified ListPin64Bit key.
11:22:28 INFO: Registry: Successfully modified FileSync key.
11:22:28 INFO: OneDrive: unable to uninstall. Exited with code: 1 - ('', "'C:\\Windows\\SysWOW64\\OneDriveSetup.exe' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n")
11:22:28 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
11:22:28 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions

```

Just wondering if that error is worth doing something about or if it's irrelevant

**Comment by monsieurpouet** [comment]
Same issue !

**Comment by Ruined1** [comment]
```
error: (1072, 'DeleteService', 'The specified service has been marked for deletion.')
```
It will be deleted on startup, this is a non-issue. The service has been successfully removed after that. I need to modify the logging to reflect that this actually isn't an issue when, if ever, I have a free moment of time.
