### ISSUE TITLE
some error about failing to remove diagtrack

### ISSUE THREAD

**Issue by overclockedllama** [10se1ucgo/DisableWinTracking#383]
Windows Home 64bit
Options used:
![image](https://user-images.githubusercontent.com/12625848/36251191-3013228e-1238-11e8-989e-ab3ee41a2170.png)

**LOG:**

```python
10:06:28 ERROR: Services: Failed to remove service 'DiagTrack'
Traceback (most recent call last):
  File "dwt_util.py", line 168, in delete_service
  File "site-packages\win32\lib\win32serviceutil.py", line 303, in RemoveService
error: (1072, 'DeleteService', 'The specified service has been marked for deletion.')
```
just thought you should know if youre not already aware

**Comment by Ruined1** [comment]
Ignore it, it's incorrect logging
