### ISSUE TITLE
OneDrive unable to uninstall, exe not found

### ISSUE THREAD

**Issue by mHasel** [10se1ucgo/DisableWinTracking#384]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Windows 10 LTSB
* Architecture (32bit/64bit): 64bit
* Options used: All

**LOG:**

```python
19:25:18 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
19:25:18 INFO: ('Windows', 'DESKTOP-7O18IO0', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')
19:25:18 INFO: DisableWinTracking version 3.2.1
19:25:29 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
19:25:29 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
19:25:29 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
19:25:29 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
19:25:29 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
19:25:29 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
19:25:29 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
19:25:29 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
19:25:29 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
19:25:29 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
19:25:29 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
19:25:29 INFO: DiagTrack: Successfully deleted service 'DiagTrack'
19:25:29 INFO: DiagTrack: Completed Part 1/3
19:25:29 INFO: DiagTrack: Successfully deleted service 'dmwappushservice'
19:25:29 INFO: DiagTrack: Completed Part 2/3
19:25:29 INFO: DiagTrack: Successfully erased tracking log.
19:25:29 INFO: DiagTrack: Completed Part 3/3
19:25:29 INFO: DiagTrack: Completed successfully, without errors.
19:25:29 ERROR: Services: Failed to remove service 'DiagTrack'
Traceback (most recent call last):
  File "dwt_util.py", line 168, in delete_service
  File "site-packages\win32\lib\win32serviceutil.py", line 303, in RemoveService
error: (1072, 'DeleteService', 'The specified service has been marked for deletion.')
19:25:29 INFO: Registry: Successfully modified dmwappushsvc key.
19:25:29 INFO: Registry: Successfully modified DiagTrack key.
19:25:29 INFO: Registry: Successfully modified AllowTelemetry key.
19:25:29 INFO: Registry: Successfully modified WifiSense Open-ness key.
19:25:29 INFO: Registry: Successfully modified WifiSense Credential Share key.
19:25:30 INFO: Registry: Successfully modified ListPin key.
19:25:30 INFO: Registry: Successfully modified ListPin64Bit key.
19:25:30 INFO: Registry: Successfully modified FileSync key.
19:25:30 INFO: OneDrive: unable to uninstall. Exited with code: 1 - ('', "'C:\\Windows\\SysWOW64\\OneDriveSetup.exe' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n")
19:25:30 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
19:25:30 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions
```

**Comment by Ruined1** [comment]
`02:32:40 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
02:32:40 INFO: ('Windows', 'DESKTOP-9G26HTS', '10', '10.0.17134', 'AMD64', 'AMD64 Family 21 Model 19 Stepping 1, AuthenticAMD')
02:32:40 INFO: DisableWinTracking version 3.2.1
02:32:47 INFO: Registry: Successfully modified ListPin key.
02:32:47 INFO: Registry: Successfully modified ListPin64Bit key.
02:32:47 INFO: Registry: Successfully modified FileSync key.
02:32:50 INFO: OneDrive: unable to uninstall. Exited with code: 0 - ('', '')
02:32:50 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
02:32:50 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions`

Code 0 means it worked, the error reporting is messed up since it says failed to uninstall, when it fact, it actually does successfully uninstall. Works fine for me on Windows 10 Version 1803 (OS Build 17134.285)
