### ISSUE TITLE
ERROR: Services: Failed to remove service 'DiagTrack'

### ISSUE THREAD

**Issue by Dumkin** [10se1ucgo/DisableWinTracking#386]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Home
* Architecture (32bit/64bit): 64bit
* Options used: 
![screenshot 2](https://user-images.githubusercontent.com/31487230/37239733-0c90b9fa-245a-11e8-9574-c1095d48017a.png)

* Clean installation, except for included **windows subsystem linux**

**LOG:**

```python
23:48:00 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
23:48:00 INFO: ('Windows', 'DESKTOP-PAM716L', '10', '10.0.16299', 'AMD64', 'AMD64 Family 21 Model 1 Stepping 2, AuthenticAMD')
23:48:00 INFO: DisableWinTracking version 3.2.1
23:49:18 INFO: DiagTrack: Successfully deleted service 'DiagTrack'
23:49:18 INFO: DiagTrack: Completed Part 1/3
23:49:18 INFO: DiagTrack: Successfully deleted service 'dmwappushservice'
23:49:18 INFO: DiagTrack: Completed Part 2/3
23:49:18 INFO: DiagTrack: Successfully erased tracking log.
23:49:18 INFO: DiagTrack: Completed Part 3/3
23:49:18 INFO: DiagTrack: Completed successfully, without errors.
23:49:21 ERROR: Services: Failed to remove service 'DiagTrack'
Traceback (most recent call last):
  File "dwt_util.py", line 168, in delete_service
  File "site-packages\win32\lib\win32serviceutil.py", line 303, in RemoveService
error: (1072, 'DeleteService', 'The specified service has been marked for deletion.')
23:49:22 INFO: Registry: Successfully modified dmwappushsvc key.
23:49:22 INFO: Registry: Successfully modified DiagTrack key.
23:49:22 INFO: Registry: Successfully modified AllowTelemetry key.
23:49:22 INFO: Registry: Successfully modified WifiSense Open-ness key.
23:49:22 INFO: Registry: Successfully modified WifiSense Credential Share key.
23:49:23 INFO: Registry: Successfully modified ListPin key.
23:49:23 INFO: Registry: Successfully modified ListPin64Bit key.
23:49:23 INFO: Registry: Successfully modified FileSync key.
23:49:26 INFO: OneDrive: unable to uninstall. Exited with code: 0 - ('', '')
23:49:26 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
23:49:26 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions

```

**Comment by Ruined1** [comment]
"The specified service has been marked for deletion" means it was successful. I dont know why it shows an error, but it did work as expected. You're good to go.
