### ISSUE TITLE
Error while disabling DiagTrack

### ISSUE THREAD

**Issue by JekRock** [10se1ucgo/DisableWinTracking#393]
**Error while disabling DiagTrack:**

* Windows Edition (Pro):
* Architecture (64bit):
* Options used:
Services, Clear DiagTrack log, Telemetry, Service Method disable
**LOG:**

```python
ERROR: Services: Failed to remove service 'DiagTrack'
Traceback (most recent call last):
  File "dwt_util.py", line 168, in delete_service
  File "site-packages\win32\lib\win32serviceutil.py", line 303, in RemoveService
error: (1072, 'DeleteService', '\xd3\xea\xe0\xe7\xe0\xed\xed\xe0\xff \xf1\xeb\xf3\xe6\xe1\xe0 \xe1\xfb\xeb\xe0 \xee\xf2\xec\xe5\xf7\xe5\xed\xe0 \xe4\xeb\xff \xf3\xe4\xe0\xeb\xe5\xed\xe8\xff.')
```

**Comment by Ruined1** [comment]
Looks like the service was already deleted or marked for deletion. Hence, the error.
