### ISSUE TITLE
Failed to remove service 'DiagTrack'

### ISSUE THREAD

**Issue by psionprime** [10se1ucgo/DisableWinTracking#398]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Home 1803
* Architecture (32bit/64bit): 64
* Options used: default

**LOG:**

```python
07:50:26 INFO: DiagTrack: Completed successfully, without errors.
07:50:26 ERROR: Services: Failed to remove service 'DiagTrack'
Traceback (most recent call last):
  File "dwt_util.py", line 168, in delete_service
  File "site-packages\win32\lib\win32serviceutil.py", line 303, in RemoveService
error: (1072, 'DeleteService', 'The specified service has been marked for deletion.')```

**Comment by Scotxd** [comment]
#383 not a bug

**Comment by Ruined1** [comment]
"The specified service has been marked for deletion" means it was successful. I dont know why it shows an error, but it did work as expected. You're good to go.
