### ISSUE TITLE
Failed to remove service 'DiagTrack'

### ISSUE THREAD

**Issue by a2rette** [10se1ucgo/DisableWinTracking#399]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): see log
* Architecture (32bit/64bit): see log
* Options used: see log

**LOG:**

```python
22:48:13 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
22:48:13 INFO: ('Windows', 'xxxxxxxx', '10', '10.0.17134', 'x86', 'x86 Family 6 Model 23 Stepping 10, GenuineIntel')
22:48:13 INFO: DisableWinTracking version 3.2.1
22:55:20 INFO: DiagTrack: Successfully deleted service 'DiagTrack'
22:55:20 INFO: DiagTrack: Completed Part 1/3
22:55:20 INFO: DiagTrack: Successfully deleted service 'dmwappushservice'
22:55:20 INFO: DiagTrack: Completed Part 2/3
22:55:20 INFO: DiagTrack: Successfully erased tracking log.
22:55:20 INFO: DiagTrack: Completed Part 3/3
22:55:20 INFO: DiagTrack: Completed successfully, without errors.
22:55:20 ERROR: Services: Failed to remove service 'DiagTrack'
Traceback (most recent call last):
  File "dwt_util.py", line 168, in delete_service
  File "site-packages\win32\lib\win32serviceutil.py", line 303, in RemoveService
error: (1072, 'DeleteService', 'Le service sp\xe9cifi\xe9 a \xe9t\xe9 marqu\xe9 pour suppression.')
22:55:21 INFO: Registry: Successfully modified dmwappushsvc key.
22:55:21 INFO: Registry: Successfully modified DiagTrack key.
22:55:21 INFO: Registry: Successfully modified AllowTelemetry key.
22:55:23 INFO: Registry: Successfully modified WifiSense Open-ness key.
22:55:23 INFO: Registry: Successfully modified WifiSense Credential Share key.
22:55:23 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
22:55:23 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions
```

**Comment by Scotxd** [comment]
#383
not a bug

**Comment by Ruined1** [comment]
"The specified service has been marked for deletion" means it was successful. I dont know why it shows an error, but it did work as expected. You're good to go.
