### ISSUE TITLE
Failed to remove service 'DiagTrack'

### ISSUE THREAD

**Issue by wolfflow** [10se1ucgo/DisableWinTracking#402]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
22:59:01 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
22:59:01 INFO: ('Windows', 'DESKTOP-HBR5DO0', '10', '10.0.10240', 'AMD64', 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel')
22:59:01 INFO: DisableWinTracking version 3.2.1
23:00:14 INFO: DiagTrack: Successfully deleted service 'DiagTrack'
23:00:14 INFO: DiagTrack: Completed Part 1/3
23:00:14 INFO: DiagTrack: Successfully deleted service 'dmwappushservice'
23:00:14 INFO: DiagTrack: Completed Part 2/3
23:00:14 INFO: DiagTrack: Successfully erased tracking log.
23:00:14 INFO: DiagTrack: Completed Part 3/3
23:00:14 INFO: DiagTrack: Completed successfully, without errors.
23:00:14 ERROR: Services: Failed to remove service 'DiagTrack'
Traceback (most recent call last):
  File "dwt_util.py", line 168, in delete_service
  File "site-packages\win32\lib\win32serviceutil.py", line 303, in RemoveService
error: (1072, 'DeleteService', 'The specified service has been marked for deletion.')
23:00:15 INFO: Registry: Successfully modified dmwappushsvc key.
23:00:15 INFO: Registry: Successfully modified DiagTrack key.
23:00:15 INFO: Registry: Successfully modified AllowTelemetry key.
23:00:15 INFO: Registry: Successfully modified WifiSense Open-ness key.
23:00:15 INFO: Registry: Successfully modified WifiSense Credential Share key.
23:00:15 INFO: Registry: Successfully modified ListPin key.
23:00:15 INFO: Registry: Successfully modified ListPin64Bit key.
23:00:15 INFO: Registry: Successfully modified FileSync key.
23:00:47 INFO: OneDrive: unable to uninstall. Exited with code: 0 - ('', '')
23:00:47 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
23:00:47 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions

```

**Comment by Ruined1** [comment]
`error: (1072, 'DeleteService', 'The specified service has been marked for deletion.')`

It's already marked for deletion.
