### ISSUE TITLE
Permission denied for hosts file edit

### ISSUE THREAD

**Issue by danieledelsale** [10se1ucgo/DisableWinTracking#423]
File host edit returns error. All the rest seems working fine.

**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Home
* Architecture (32bit/64bit): 64bit
* Options used: First all of them. The second try 'block tracking domains (with the more aggressive one) and the IP addresses

**LOG:**

```python
18:15:01 INFO: Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)] on win32
18:15:01 INFO: ('Windows', 'delsi-XPS', '10', '10.0.17763', 'AMD64', 'Intel64 Family 6 Model 158 Stepping 10, GenuineIntel')
18:15:01 INFO: DisableWinTracking version 3.2.3
18:15:50 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
18:15:51 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
18:15:51 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
18:15:51 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
18:15:51 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
18:15:51 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
18:15:51 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
18:15:51 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
18:15:52 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
18:15:52 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
18:15:52 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
18:15:52 INFO: DiagTrack: Successfully deleted service 'DiagTrack'
18:15:52 INFO: DiagTrack: Completed Part 1/3
18:15:52 INFO: DiagTrack: Successfully deleted service 'dmwappushservice'
18:15:52 INFO: DiagTrack: Completed Part 2/3
18:15:52 INFO: DiagTrack: Successfully erased tracking log.
18:15:52 INFO: DiagTrack: Completed Part 3/3
18:15:52 INFO: DiagTrack: Completed successfully, without errors.
18:15:52 INFO: Registry: Successfully modified dmwappushsvc key.
18:15:52 INFO: Registry: Successfully modified DiagTrack key.
18:15:52 INFO: Registry: Successfully modified AllowTelemetry key.
18:15:52 ERROR: Hosts: Failed to modify hosts file
Traceback (most recent call last):
  File "dwt_util.py", line 312, in host_file
IOError: [Errno 13] Permission denied: 'C:\\Windows\\System32/drivers/etc/hosts'
18:15:52 ERROR: Hosts: Failed to modify hosts file
Traceback (most recent call last):
  File "dwt_util.py", line 312, in host_file
IOError: [Errno 13] Permission denied: 'C:\\Windows\\System32/drivers/etc/hosts'
18:15:52 INFO: Registry: Successfully modified WifiSense Open-ness key.
18:15:52 INFO: Registry: Successfully modified WifiSense Credential Share key.
18:15:53 INFO: Registry: Successfully modified ListPin key.
18:15:53 INFO: Registry: Successfully modified ListPin64Bit key.
18:15:53 INFO: Registry: Successfully modified FileSync key.
18:16:16 INFO: OneDrive: successfully uninstalled
18:16:17 INFO: Registry: Successfully modified GameDVR_Enabled key.
18:16:17 INFO: Registry: Successfully modified AllowGameDVR key.
18:16:17 INFO: Xbox DVR: successfully disabled
18:16:17 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
18:16:17 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions
18:16:47 INFO: Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)] on win32
18:16:47 INFO: ('Windows', 'delsi-XPS', '10', '10.0.17763', 'AMD64', 'Intel64 Family 6 Model 158 Stepping 10, GenuineIntel')
18:16:47 INFO: DisableWinTracking version 3.2.3
18:16:54 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
18:16:54 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
18:16:54 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
18:16:55 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
18:16:55 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
18:16:55 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
18:16:55 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
18:16:55 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
18:16:55 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
18:16:55 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
18:16:56 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
18:16:56 ERROR: Hosts: Failed to modify hosts file
Traceback (most recent call last):
  File "dwt_util.py", line 312, in host_file
IOError: [Errno 13] Permission denied: 'C:\\Windows\\System32/drivers/etc/hosts'
18:16:56 ERROR: Hosts: Failed to modify hosts file
Traceback (most recent call last):
  File "dwt_util.py", line 312, in host_file
IOError: [Errno 13] Permission denied: 'C:\\Windows\\System32/drivers/etc/hosts'
18:16:56 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
18:16:56 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions

```

**Comment by Ruined1** [comment]
This was likely caused by some form of security software. Did you try disabling and anti-virus software present before running this? (AVG, Antivir, Malwarebytes, Norton, etc)

**Comment by Ruined1** [comment]
Successfully tested on Windows 10 Pro 64-bit. No Issues:
```
10:13:39 INFO: Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
10:13:39 INFO: uname_result(system='Windows', node='DESKTOP-PHQRIIU', release='10', version='10.0.17763', machine='AMD64', processor='AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD')
10:13:39 INFO: DisableWinTracking version 3.2.3
10:13:59 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
10:13:59 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
10:14:00 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
10:14:00 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
10:14:00 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
10:14:00 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
10:14:00 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
10:14:00 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
10:14:00 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
10:14:00 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
10:14:00 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
10:14:00 INFO: DiagTrack: Successfully deleted service 'DiagTrack'
10:14:00 INFO: DiagTrack: Completed Part 1/3
10:14:00 INFO: DiagTrack: Successfully deleted service 'dmwappushservice'
10:14:00 INFO: DiagTrack: Completed Part 2/3
10:14:00 INFO: DiagTrack: Successfully erased tracking log.
10:14:00 INFO: DiagTrack: Completed Part 3/3
10:14:00 INFO: DiagTrack: Completed successfully, without errors.
10:14:01 INFO: Registry: Successfully modified dmwappushsvc key.
10:14:01 INFO: Registry: Successfully modified DiagTrack key.
10:14:01 INFO: Registry: Successfully modified AllowTelemetry key.
10:14:01 INFO: Registry: Successfully modified WifiSense Credential Share key.
10:14:01 INFO: Registry: Successfully modified WifiSense Open-ness key.
10:14:01 INFO: Registry: Successfully modified FileSync key.
10:14:01 INFO: Registry: Successfully modified ListPin key.
10:14:01 INFO: OneDrive: Binary doesn't exist. Unable to uninstall. Do not send a report for this.
10:14:02 INFO: Registry: Successfully modified GameDVR_Enabled key.
10:14:02 INFO: Registry: Successfully modified AllowGameDVR key.
10:14:02 INFO: Xbox DVR: successfully disabled
10:14:02 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
10:14:02 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions
```
