### ISSUE TITLE
permisson denied

### ISSUE THREAD

**Issue by dxbmax** [10se1ucgo/DisableWinTracking#456]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Win10Pro
* Architecture (32bit/64bit): Intel64
* Options used:
all except wifisense, disable, privacy
console output shows permission to hosts was denied but I ran this as admin.
Appreciate your help

**LOG:**

```python
21:33:39 INFO: DisableWinTracking version 3.2.3
21:34:54 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
21:34:54 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
21:34:54 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
21:34:54 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
21:34:54 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
21:34:54 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
21:34:54 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
21:34:54 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
21:34:54 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
21:34:55 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
21:34:55 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
21:34:55 INFO: DiagTrack: DiagTrack service doesn't exist. This is OK, you likely removed it already.
21:34:55 INFO: DiagTrack: Completed Part 1/3
21:34:55 INFO: DiagTrack: dmwappushservice service doesn't exist. This is OK, you likely removed it already.
21:34:55 INFO: DiagTrack: Completed Part 2/3
21:34:55 INFO: DiagTrack: Successfully erased tracking log.
21:34:55 INFO: DiagTrack: Completed Part 3/3
21:34:55 INFO: DiagTrack: Completed successfully, without errors.
21:34:55 INFO: Registry: Successfully modified dmwappushsvc key.
21:34:55 INFO: Registry: Successfully modified DiagTrack key.
21:34:55 INFO: Registry: Successfully modified AllowTelemetry key.
21:34:55 ERROR: Hosts: Failed to modify hosts file
Traceback (most recent call last):
  File "dwt_util.py", line 312, in host_file
IOError: [Errno 13] Permission denied: 'C:\\Windows\\System32/drivers/etc/hosts'
21:34:55 ERROR: Hosts: Failed to modify hosts file
Traceback (most recent call last):
  File "dwt_util.py", line 312, in host_file
IOError: [Errno 13] Permission denied: 'C:\\Windows\\System32/drivers/etc/hosts'
21:34:55 INFO: Registry: Successfully modified ListPin key.
21:34:55 INFO: Registry: Successfully modified ListPin64Bit key.
21:34:55 INFO: Registry: Successfully modified FileSync key.
21:34:58 INFO: OneDrive: successfully uninstalled
21:34:58 INFO: Registry: Successfully modified GameDVR_Enabled key.
21:34:58 INFO: Registry: Successfully modified AllowGameDVR key.
21:34:58 INFO: Xbox DVR: successfully disabled
21:34:58 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
21:34:58 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions

```

**Comment by Chaython** [comment]
Did you run as admin? Make sure the host file is not marked as read only.
Do you have python?
________________________________

**Comment by dxbmax** [comment]
Yes, ran as admin. host file not marked read-only. yes I have python. missed first 2 lines of the log

### 
21:33:39 INFO: Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)] on win32
21:33:39 INFO: ('Windows', 'DESKTOP-1T0VMHL', '10', '10.0.17763', 'AMD64', 'Intel64 Family 6 Model 69 Stepping 1, GenuineIntel')
21:33:39 INFO: DisableWinTracking version 3.2.3

**Comment by Chaython** [comment]
Sorry, i can't help further.
This has been dead for over a year.
Most modifications are still relevant but don't really work anymore.
If you just want to block MS then https://github.com/crazy-max/WindowsSpyBlocker
However I reccomend https://github.com/henrypp/simplewall Its a WFP GUI, by far the best FOSS firewall for windows, it has options to disable and block all MS services. Easily togglable. if you ever wanted to use the services... [It integrates WindowsSpyBlocker]

**Comment by dxbmax** [comment]
Thanks for your suggestion, simplewall is great!
