### ISSUE TITLE
CRITICAL: DiagTrack: Error code: 1 - ('', "'sc' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n")

### ISSUE THREAD

**Issue by Tymoteusz12** [10se1ucgo/DisableWinTracking#458]
**INFORMATION:**

* Windows 10 Home:
* Architecture 64bit
* Options used:
All current available. Everything works fine for 3 selected:
Block tracking domains, more tracking domains and ip adresses

**LOG:**

```python
22:11:58 INFO: DisableWinTracking version 3.2.3
22:12:08 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
22:12:08 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
22:12:08 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
22:12:08 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
22:12:08 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
22:12:08 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
22:12:08 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
22:12:08 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
22:12:09 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
22:12:09 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
22:12:09 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
22:12:09 INFO: 1
22:12:09 ERROR: DiagTrack: Failed Part 1/3
None
22:12:09 CRITICAL: DiagTrack: Error code: 1 - ('', "'sc' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n")
22:12:09 INFO: 1
22:12:09 ERROR: DiagTrack: Failed Part 2/3
None
22:12:09 CRITICAL: DiagTrack: Error code: 1 - ('', "'sc' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n")
22:12:09 INFO: DiagTrack: Successfully erased tracking log.
22:12:09 INFO: DiagTrack: Completed Part 3/3
22:12:09 INFO: DiagTrack: Complete. Errors were recorded.
22:12:09 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 311, in go
  File "dwt_util.py", line 205, in services
  File "dwt_util.py", line 282, in set_registry
  File "dwt_util.py", line 69, in is_64bit
  File "subprocess.py", line 216, in check_output
  File "subprocess.py", line 394, in __init__
  File "subprocess.py", line 644, in _execute_child
WindowsError: [Error 2] Nie można odnaleźć określonego pliku - Which means "Cannot find specified file"
```

**Comment by DeeJayhX** [comment]
![image](https://user-images.githubusercontent.com/1514573/103204732-da5c7800-48ac-11eb-9f11-5cc93b5fbdb4.png)
