### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by jeremy54000** [10se1ucgo/DisableWinTracking#72]
22:50:12 ERROR: Registry: Unable to modify Service dmwappushsvc key.
Traceback (most recent call last):
  File "<string>", line 474, in modifyregistry
WindowsError: [Error 2] Le fichier spécifié est introuvable

22:50:12 ERROR: Services: dmwappushsvc unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 358, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 320, in ControlService
error: (1062, 'ControlService', 'Le service n\x92a pas \xe9t\xe9 d\xe9marr\xe9.')

22:50:12 ERROR: Services: Diagnostics Tracking Service unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 358, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'Le service sp\xe9cifi\xe9 n\x92existe pas en tant que service install\xe9.')

23:09:20 ERROR: Registry: Unable to modify Service dmwappushsvc key.
Traceback (most recent call last):
  File "<string>", line 474, in modifyregistry
WindowsError: [Error 2] Le fichier spécifié est introuvable

23:09:20 ERROR: Services: dmwappushsvc unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 358, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 320, in ControlService
error: (1062, 'ControlService', 'Le service n\x92a pas \xe9t\xe9 d\xe9marr\xe9.')

23:09:20 ERROR: Services: Diagnostics Tracking Service unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 358, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'Le service sp\xe9cifi\xe9 n\x92existe pas en tant que service install\xe9.')

**Comment by Ruined1** [comment]
It's truly amazing to me that no one checks previous bug reports before filing new ones...
https://github.com/10se1ucgo/DisableWinTracking/issues/71
https://github.com/10se1ucgo/DisableWinTracking/issues/70
https://github.com/10se1ucgo/DisableWinTracking/issues/68
