### ISSUE TITLE
Some complaints in DisableWinTracking.log

### ISSUE THREAD

**Issue by arnstein99** [10se1ucgo/DisableWinTracking#74]
I cannot figure out how to attach a file. So here is DisableWinTracking.log, in line:

17:47:48 ERROR: Registry: Unable to modify Service dmwappushsvc key.
Traceback (most recent call last):
  File "<string>", line 473, in modifyregistry
WindowsError: [Error 2] The system cannot find the file specified

17:47:48 ERROR: Services: dmwappushsvc unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 357, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 320, in ControlService
error: (1062, 'ControlService', 'The service has not been started.')

17:47:48 ERROR: Services: Diagnostics Tracking Service unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 357, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 320, in ControlService
error: (1061, 'ControlService', 'The service cannot accept control messages at this time.')

**Comment by 10se1ucgo** [comment]
If you've ran thwith program before this is OK.
