### ISSUE TITLE
ERROR: Registry: Unable to modify Service dmwappushsvc key

### ISSUE THREAD

**Issue by kurapikats** [10se1ucgo/DisableWinTracking#75]
I got this from DisableWinTracking.log
I'm using v2.4.1 

12:29:46 ERROR: Registry: Unable to modify Service dmwappushsvc key.
Traceback (most recent call last):
  File "<string>", line 473, in modifyregistry
WindowsError: [Error 2] The system cannot find the file specified

12:29:46 ERROR: Services: dmwappushsvc unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 357, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 320, in ControlService
error: (1062, 'ControlService', 'The service has not been started.')

12:29:46 ERROR: Services: Diagnostics Tracking Service unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 357, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 320, in ControlService
error: (1061, 'ControlService', 'The service cannot accept control messages at this time.')

**Comment by 10se1ucgo** [comment]
If you've run this program before it's OK to have these errors.
