### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by 10se1ucgo** [10se1ucgo/DisableWinTracking#78]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Home
* Architecture (32bit/64bit): 64bit
* Options used: Services, Telemetry, Block domains.

**LOG:**

```python

18:31:35 INFO: DisableWinTracking Version: v2.4.3

18:31:35 ERROR: Services: dmwappushsvc unable to be stopped. THIS IS ONLY AN ISSUE IF THIS IS YOUR FIRST TIME RUNNING THIS PROGRAM! Please DO NOT submit issues on GitHub otherwise.
Traceback (most recent call last):
  File "<string>", line 373, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'The specified service does not exist as an installed service.')

18:31:35 ERROR: Services: Diagnostics Tracking Service unable to be stopped. THIS IS ONLY AN ISSUE IF THIS IS YOUR FIRST TIME RUNNING THIS PROGRAM! Please DO NOT submit issues on GitHub otherwise.
Traceback (most recent call last):
  File "<string>", line 373, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'The specified service does not exist as an installed service.')

18:31:35 ERROR: Services: Diagnostics Tracking Service unable to be stopped. THIS IS ONLY AN ISSUE IF THIS IS YOUR FIRST TIME RUNNING THIS PROGRAM! Please DO NOT submit issues on GitHub otherwise.
Traceback (most recent call last):
  File "<string>", line 373, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'The specified service does not exist as an installed service.')

18:31:37 ERROR: Registry: Unable to modify Windows Defender Spynet key.
Traceback (most recent call last):
  File "<string>", line 487, in modifyregistry
WindowsError: [Error 5] Access is denied

18:31:37 ERROR: Registry: Unable to modify Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "<string>", line 487, in modifyregistry
WindowsError: [Error 5] Access is denied

```

**Comment by Ruined1** [comment]
So we're still having issues with the registry keys.

**Comment by 10se1ucgo** [comment]
@Ruined1 Nah, it's just that Windows Defender is protected, probably to prevent malware infecting it.

**Comment by Ruined1** [comment]
@10se1ucgo ah just noticed that
