### ISSUE TITLE
Permission denied even with Run As Administrator

### ISSUE THREAD

**Issue by cryzies** [10se1ucgo/DisableWinTracking#79]
15:57:49 INFO: DisableWinTracking Version: 2.4.3

15:57:49 ERROR: Services: dmwappushsvc unable to be stopped. THIS IS ONLY AN ISSUE IF THIS IS YOUR FIRST TIME RUNNING THIS PROGRAM! Please DO NOT submit issues on GitHub otherwise.
Traceback (most recent call last):
  File "<string>", line 373, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 320, in ControlService
error: (1062, 'ControlService', 'The service has not been started.')

15:57:49 ERROR: Services: Diagnostics Tracking Service unable to be stopped. THIS IS ONLY AN ISSUE IF THIS IS YOUR FIRST TIME RUNNING THIS PROGRAM! Please DO NOT submit issues on GitHub otherwise.
Traceback (most recent call last):
  File "<string>", line 373, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 320, in ControlService
error: (1062, 'ControlService', 'The service has not been started.')

15:57:49 ERROR: Services: Diagnostics Tracking Service unable to be stopped. THIS IS ONLY AN ISSUE IF THIS IS YOUR FIRST TIME RUNNING THIS PROGRAM! Please DO NOT submit issues on GitHub otherwise.
Traceback (most recent call last):
  File "<string>", line 373, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 320, in ControlService
error: (1062, 'ControlService', 'The service has not been started.')

15:57:50 ERROR: Registry: Unable to modify Windows Defender Spynet key.
Traceback (most recent call last):
  File "<string>", line 487, in modifyregistry
WindowsError: [Error 5] Access is denied

15:57:50 ERROR: Registry: Unable to modify Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "<string>", line 487, in modifyregistry
WindowsError: [Error 5] Access is denied

22:50:10 INFO: DisableWinTracking Version: 2.4.3

22:50:10 ERROR: Services: Diagnostics Tracking Service unable to be stopped. THIS IS ONLY AN ISSUE IF THIS IS YOUR FIRST TIME RUNNING THIS PROGRAM! Please DO NOT submit issues on GitHub otherwise.
Traceback (most recent call last):
  File "<string>", line 373, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'The specified service does not exist as an installed service.')

22:50:12 ERROR: Registry: Unable to modify Windows Defender Spynet key.
Traceback (most recent call last):
  File "<string>", line 487, in modifyregistry
WindowsError: [Error 5] Access is denied

22:50:12 ERROR: Registry: Unable to modify Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "<string>", line 487, in modifyregistry
WindowsError: [Error 5] Access is denied

22:50:56 INFO: DisableWinTracking Version: 2.4.3

22:50:56 ERROR: Services: dmwappushsvc unable to be stopped. THIS IS ONLY AN ISSUE IF THIS IS YOUR FIRST TIME RUNNING THIS PROGRAM! Please DO NOT submit issues on GitHub otherwise.
Traceback (most recent call last):
  File "<string>", line 373, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'The specified service does not exist as an installed service.')

22:50:56 ERROR: Services: Diagnostics Tracking Service unable to be stopped. THIS IS ONLY AN ISSUE IF THIS IS YOUR FIRST TIME RUNNING THIS PROGRAM! Please DO NOT submit issues on GitHub otherwise.
Traceback (most recent call last):
  File "<string>", line 373, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'The specified service does not exist as an installed service.')

22:50:56 ERROR: Services: Diagnostics Tracking Service unable to be stopped. THIS IS ONLY AN ISSUE IF THIS IS YOUR FIRST TIME RUNNING THIS PROGRAM! Please DO NOT submit issues on GitHub otherwise.
Traceback (most recent call last):
  File "<string>", line 373, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'The specified service does not exist as an installed service.')

22:50:57 ERROR: Registry: Unable to modify Windows Defender Spynet key.
Traceback (most recent call last):
  File "<string>", line 487, in modifyregistry
WindowsError: [Error 5] Access is denied

22:50:57 ERROR: Registry: Unable to modify Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "<string>", line 487, in modifyregistry
WindowsError: [Error 5] Access is denied

22:51:01 INFO: DisableWinTracking Version: 2.4.3

22:51:01 ERROR: Services: dmwappushsvc unable to be deleted. THIS IS ONLY AN ISSUE IF THIS IS YOUR FIRST TIME RUNNING THIS PROGRAM! Please DO NOT submit issues on GitHub otherwise.
Traceback (most recent call last):
  File "<string>", line 363, in deleteservice
  File "disablewintracking\win32serviceutil", line 302, in RemoveService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'The specified service does not exist as an installed service.')

22:51:01 ERROR: Services: Diagnostics Tracking Service unable to be deleted. THIS IS ONLY AN ISSUE IF THIS IS YOUR FIRST TIME RUNNING THIS PROGRAM! Please DO NOT submit issues on GitHub otherwise.
Traceback (most recent call last):
  File "<string>", line 363, in deleteservice
  File "disablewintracking\win32serviceutil", line 302, in RemoveService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'The specified service does not exist as an installed service.')

22:51:01 ERROR: Services: Diagnostics Tracking Service unable to be stopped. THIS IS ONLY AN ISSUE IF THIS IS YOUR FIRST TIME RUNNING THIS PROGRAM! Please DO NOT submit issues on GitHub otherwise.
Traceback (most recent call last):
  File "<string>", line 373, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'The specified service does not exist as an installed service.')

22:51:02 ERROR: Registry: Unable to modify Windows Defender Spynet key.
Traceback (most recent call last):
  File "<string>", line 487, in modifyregistry
WindowsError: [Error 5] Access is denied

22:51:02 ERROR: Registry: Unable to modify Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "<string>", line 487, in modifyregistry
WindowsError: [Error 5] Access is denied

**Comment by Ruined1** [comment]
Yup we're well aware of the issue and I'm currently developing to bypass it. The services messages you can ignore, they are expected and not an issue, the "Access is Denied" results are the one's I'm working on.
