### ISSUE TITLE
Cannot remove/append domains, and unable to modify two Windows Defender keys.

### ISSUE THREAD

**Issue by alexschrank** [10se1ucgo/DisableWinTracking#85]
Log report below. I right-clicked on the program and chose "run as administrator" so that should not be the issue here.

03:05:36 ERROR: Domain block: Could not remove domains.
Traceback (most recent call last):
  File "<string>", line 530, in modifyhostfile
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'C:\\windows\\System32\\drivers\\etc\\hosts'

03:05:36 ERROR: Extra domain block: Could not remove domains.
Traceback (most recent call last):
  File "<string>", line 530, in modifyhostfile
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'C:\\windows\\System32\\drivers\\etc\\hosts'

03:05:36 INFO: DisableWinTracking Version: 2.4.3

03:05:37 ERROR: Domain block: Could not append domains
Traceback (most recent call last):
  File "<string>", line 516, in modifyhostfile
IOError: [Errno 13] Permission denied: 'C:\\windows\\System32\\drivers\\etc\\hosts'

03:05:37 ERROR: Extra domain block: Could not append domains
Traceback (most recent call last):
  File "<string>", line 516, in modifyhostfile
IOError: [Errno 13] Permission denied: 'C:\\windows\\System32\\drivers\\etc\\hosts'

03:05:38 ERROR: Registry: Unable to modify Windows Defender Spynet key.
Traceback (most recent call last):
  File "<string>", line 487, in modifyregistry
WindowsError: [Error 5] Access is denied

03:05:38 ERROR: Registry: Unable to modify Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "<string>", line 487, in modifyregistry
WindowsError: [Error 5] Access is denied

**Comment by Ruined1** [comment]
## These are okay:
> 03:05:38 ERROR: Registry: Unable to modify Windows Defender Spynet key.
Traceback (most recent call last):
File "", line 487, in modifyregistry
WindowsError: [Error 5] Access is denied

03:05:38 ERROR: Registry: Unable to modify Windows Defender Sample Submission key.
Traceback (most recent call last):
File "", line 487, in modifyregistry
WindowsError: [Error 5] Access is denied

## These are because something is blocking access to your hosts file (antivirus running?)
> 03:05:37 ERROR: Domain block: Could not append domains
Traceback (most recent call last):
File "", line 516, in modifyhostfile
IOError: [Errno 13] Permission denied: 'C:\windows\System32\drivers\etc\hosts'

03:05:37 ERROR: Extra domain block: Could not append domains
Traceback (most recent call last):
File "", line 516, in modifyhostfile
IOError: [Errno 13] Permission denied: 'C:\windows\System32\drivers\etc\hosts'

## These are because the hosts file was open in another program (also antivirus?)
> 03:05:36 ERROR: Domain block: Could not remove domains.
Traceback (most recent call last):
File "", line 530, in modifyhostfile
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'C:\windows\System32\drivers\etc\hosts'

03:05:36 ERROR: Extra domain block: Could not remove domains.
Traceback (most recent call last):
File "", line 530, in modifyhostfile
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'C:\windows\System32\drivers\etc\hosts'

# My Suggestion

Temporarily disable any security software and try running as admin again, then repost log.

**Comment by alexschrank** [comment]
Sorry, that worked, thank you!
