### ISSUE TITLE
multiple error 5

### ISSUE THREAD

**Issue by szalony** [10se1ucgo/DisableWinTracking#97]
**INFORMATION:**

* W10 home
* 64bit
* Options used: all

**LOG:**

```python

18:23:24 INFO: Performing clutter control

18:23:25 INFO: DiagTrack box ticked

18:23:25 ERROR: Services: Diagnostics Tracking Service unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 474, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'De opgegeven service is geen ge\xefnstalleerde service.')

18:23:25 INFO: Service disable option ticked

18:23:25 ERROR: Services: dmwappushsvc unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 474, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'De opgegeven service is geen ge\xefnstalleerde service.')

18:23:25 ERROR: Services: Diagnostics Tracking Service unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 474, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'De opgegeven service is geen ge\xefnstalleerde service.')

18:23:25 INFO: DisableWinTracking Version: v2.5.1

18:23:25 INFO: Mode: Privacy

18:23:25 INFO: Telemetry box ticked

18:23:25 INFO: Host box ticked

18:23:25 INFO: Extra host box ticked

18:23:25 INFO: IP block box ticked

18:23:26 INFO: Defender/Wifisense box ticked

18:23:26 ERROR: Registry: Unable to modify Windows Defender Spynet key.
Traceback (most recent call last):
  File "<string>", line 575, in modifyregistry
WindowsError: [Error 5] Toegang geweigerd

18:23:26 ERROR: Registry: Unable to modify Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "<string>", line 575, in modifyregistry
WindowsError: [Error 5] Toegang geweigerd

18:23:26 INFO: OneDrive box ticked

```

**Comment by Ruined1** [comment]
Alles in het dagboek is prima. Negeer deze fouten , ging alles perfect.

**Comment by 10se1ucgo** [comment]
Ahh, my error checking did not account for non-English languages. I'm dumb :P

**Comment by 10se1ucgo** [comment]
Fixed in 988bb5c059f5fab75e5826e9e436c6f8882053a1

sorry :S

**Comment by szalony** [comment]
Thanks :)

Not working yet tho, runned is as admin:

Toegang geweigerd (dutch) =  Access denied

15:59:14 INFO: Performing clutter control

15:59:16 INFO: DiagTrack box ticked

15:59:16 ERROR: Services: Diagnostics Tracking Service unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 474, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'De opgegeven service is geen ge\xefnstalleerde service.')

15:59:16 INFO: Service disable option ticked

15:59:16 ERROR: Services: dmwappushsvc unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 474, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'De opgegeven service is geen ge\xefnstalleerde service.')

15:59:16 ERROR: Services: Diagnostics Tracking Service unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 474, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'De opgegeven service is geen ge\xefnstalleerde service.')

15:59:16 INFO: DisableWinTracking Version: v2.5.1

15:59:16 INFO: Mode: Privacy

15:59:17 INFO: Telemetry box ticked

15:59:17 INFO: Host box ticked

15:59:17 INFO: Extra host box ticked

15:59:17 INFO: IP block box ticked

15:59:19 INFO: Defender/Wifisense box ticked

15:59:19 ERROR: Registry: Unable to modify Windows Defender Spynet key.
Traceback (most recent call last):
  File "<string>", line 575, in modifyregistry
WindowsError: [Error 5] Toegang geweigerd

15:59:19 ERROR: Registry: Unable to modify Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "<string>", line 575, in modifyregistry
WindowsError: [Error 5] Toegang geweigerd

15:59:19 INFO: OneDrive box ticked

15:59:21 INFO: Performing clutter control

15:59:23 INFO: DiagTrack box ticked

15:59:23 ERROR: Services: Diagnostics Tracking Service unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 474, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'De opgegeven service is geen ge\xefnstalleerde service.')

15:59:24 INFO: Service disable option ticked

15:59:24 ERROR: Services: dmwappushsvc unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 474, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'De opgegeven service is geen ge\xefnstalleerde service.')

15:59:24 ERROR: Services: Diagnostics Tracking Service unable to be stopped.
Traceback (most recent call last):
  File "<string>", line 474, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 318, in ControlService
  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
error: (1060, 'GetServiceKeyName', 'De opgegeven service is geen ge\xefnstalleerde service.')

15:59:24 INFO: DisableWinTracking Version: v2.5.1

15:59:24 INFO: Mode: Privacy

15:59:24 INFO: Telemetry box ticked

15:59:24 INFO: Host box ticked

15:59:24 INFO: Extra host box ticked

15:59:24 INFO: IP block box ticked

15:59:26 INFO: Defender/Wifisense box ticked

15:59:26 ERROR: Registry: Unable to modify Windows Defender Spynet key.
Traceback (most recent call last):
  File "<string>", line 575, in modifyregistry
WindowsError: [Error 5] Toegang geweigerd

15:59:26 ERROR: Registry: Unable to modify Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "<string>", line 575, in modifyregistry
WindowsError: [Error 5] Toegang geweigerd

15:59:26 INFO: OneDrive box ticked


Date: Mon, 5 Oct 2015 16:44:33 -0700

**Comment by Ruined1** [comment]
@szalony de eerste keer dat je liep het programma , heb je DELETE van de diensten , of uit te schakelen hen ? Als u verwijderd van de diensten , fouten dan over de service niet bestaat juist zijn .

**Comment by szalony** [comment]
Could be, tried a couple of things. Anyway to check?

**Comment by Ruined1** [comment]
@szalony Ja. klik met de rechtermuisknop op de startknop en ga naar " Computerbeheer " . In het linker tabblad open " Services en toepassingen " en klik op " diensten " . Dan kunt u zien of deze diensten zijn er of niet . Als ze niet , ze werden eerder verwijderde .

Op een kanttekening, het hoofd Developer noemde hij een probleem met andere talen dan Engels vast . Wachten tot hij stelt een nieuwe uitvoerbare binaire en probeer de nieuwste versie om te zien of deze is opgelost.
